/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type Codec,
	combineCodec,
	type Decoder,
	type Encoder,
	type GetDiscriminatedUnionVariant,
	type GetDiscriminatedUnionVariantContent,
	getDiscriminatedUnionDecoder,
	getDiscriminatedUnionEncoder,
	getStructDecoder,
	getStructEncoder,
	getTupleDecoder,
	getTupleEncoder
} from "@solana/kit"
import {
	type BoardInitialized,
	type BoardInitializedArgs,
	getBoardInitializedDecoder,
	getBoardInitializedEncoder,
	getMessageDeletedDecoder,
	getMessageDeletedEncoder,
	getMessagePostedDecoder,
	getMessagePostedEncoder,
	getProfileCreatedDecoder,
	getProfileCreatedEncoder,
	getProfileSuspendedDecoder,
	getProfileSuspendedEncoder,
	getUsernameUpdatedDecoder,
	getUsernameUpdatedEncoder,
	type MessageDeleted,
	type MessageDeletedArgs,
	type MessagePosted,
	type MessagePostedArgs,
	type ProfileCreated,
	type ProfileCreatedArgs,
	type ProfileSuspended,
	type ProfileSuspendedArgs,
	type UsernameUpdated,
	type UsernameUpdatedArgs
} from "."

export type BoardEvent =
	| { __kind: "BoardInitialized"; fields: readonly [BoardInitialized] }
	| { __kind: "ProfileCreated"; fields: readonly [ProfileCreated] }
	| { __kind: "UsernameUpdated"; fields: readonly [UsernameUpdated] }
	| { __kind: "MessagePosted"; fields: readonly [MessagePosted] }
	| { __kind: "MessageDeleted"; fields: readonly [MessageDeleted] }
	| { __kind: "ProfileSuspended"; fields: readonly [ProfileSuspended] }

export type BoardEventArgs =
	| { __kind: "BoardInitialized"; fields: readonly [BoardInitializedArgs] }
	| { __kind: "ProfileCreated"; fields: readonly [ProfileCreatedArgs] }
	| { __kind: "UsernameUpdated"; fields: readonly [UsernameUpdatedArgs] }
	| { __kind: "MessagePosted"; fields: readonly [MessagePostedArgs] }
	| { __kind: "MessageDeleted"; fields: readonly [MessageDeletedArgs] }
	| { __kind: "ProfileSuspended"; fields: readonly [ProfileSuspendedArgs] }

export function getBoardEventEncoder(): Encoder<BoardEventArgs> {
	return getDiscriminatedUnionEncoder([
		[
			"BoardInitialized",
			getStructEncoder([["fields", getTupleEncoder([getBoardInitializedEncoder()])]])
		],
		[
			"ProfileCreated",
			getStructEncoder([["fields", getTupleEncoder([getProfileCreatedEncoder()])]])
		],
		[
			"UsernameUpdated",
			getStructEncoder([["fields", getTupleEncoder([getUsernameUpdatedEncoder()])]])
		],
		["MessagePosted", getStructEncoder([["fields", getTupleEncoder([getMessagePostedEncoder()])]])],
		[
			"MessageDeleted",
			getStructEncoder([["fields", getTupleEncoder([getMessageDeletedEncoder()])]])
		],
		[
			"ProfileSuspended",
			getStructEncoder([["fields", getTupleEncoder([getProfileSuspendedEncoder()])]])
		]
	])
}

export function getBoardEventDecoder(): Decoder<BoardEvent> {
	return getDiscriminatedUnionDecoder([
		[
			"BoardInitialized",
			getStructDecoder([["fields", getTupleDecoder([getBoardInitializedDecoder()])]])
		],
		[
			"ProfileCreated",
			getStructDecoder([["fields", getTupleDecoder([getProfileCreatedDecoder()])]])
		],
		[
			"UsernameUpdated",
			getStructDecoder([["fields", getTupleDecoder([getUsernameUpdatedDecoder()])]])
		],
		["MessagePosted", getStructDecoder([["fields", getTupleDecoder([getMessagePostedDecoder()])]])],
		[
			"MessageDeleted",
			getStructDecoder([["fields", getTupleDecoder([getMessageDeletedDecoder()])]])
		],
		[
			"ProfileSuspended",
			getStructDecoder([["fields", getTupleDecoder([getProfileSuspendedDecoder()])]])
		]
	])
}

export function getBoardEventCodec(): Codec<BoardEventArgs, BoardEvent> {
	return combineCodec(getBoardEventEncoder(), getBoardEventDecoder())
}

// Data Enum Helpers.
export function boardEvent(
	kind: "BoardInitialized",
	data: GetDiscriminatedUnionVariantContent<BoardEventArgs, "__kind", "BoardInitialized">["fields"]
): GetDiscriminatedUnionVariant<BoardEventArgs, "__kind", "BoardInitialized">
export function boardEvent(
	kind: "ProfileCreated",
	data: GetDiscriminatedUnionVariantContent<BoardEventArgs, "__kind", "ProfileCreated">["fields"]
): GetDiscriminatedUnionVariant<BoardEventArgs, "__kind", "ProfileCreated">
export function boardEvent(
	kind: "UsernameUpdated",
	data: GetDiscriminatedUnionVariantContent<BoardEventArgs, "__kind", "UsernameUpdated">["fields"]
): GetDiscriminatedUnionVariant<BoardEventArgs, "__kind", "UsernameUpdated">
export function boardEvent(
	kind: "MessagePosted",
	data: GetDiscriminatedUnionVariantContent<BoardEventArgs, "__kind", "MessagePosted">["fields"]
): GetDiscriminatedUnionVariant<BoardEventArgs, "__kind", "MessagePosted">
export function boardEvent(
	kind: "MessageDeleted",
	data: GetDiscriminatedUnionVariantContent<BoardEventArgs, "__kind", "MessageDeleted">["fields"]
): GetDiscriminatedUnionVariant<BoardEventArgs, "__kind", "MessageDeleted">
export function boardEvent(
	kind: "ProfileSuspended",
	data: GetDiscriminatedUnionVariantContent<BoardEventArgs, "__kind", "ProfileSuspended">["fields"]
): GetDiscriminatedUnionVariant<BoardEventArgs, "__kind", "ProfileSuspended">
export function boardEvent<K extends BoardEventArgs["__kind"], Data>(kind: K, data?: Data) {
	return Array.isArray(data) ? { __kind: kind, fields: data } : { __kind: kind, ...(data ?? {}) }
}

export function isBoardEvent<K extends BoardEvent["__kind"]>(
	kind: K,
	value: BoardEvent
): value is BoardEvent & { __kind: K } {
	return value.__kind === kind
}
