/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	fixDecoderSize,
	fixEncoderSize,
	getBytesDecoder,
	getBytesEncoder,
	getStructDecoder,
	getStructEncoder,
	getU64Decoder,
	getU64Encoder,
	type ReadonlyUint8Array
} from "@solana/kit"

export type BoardInitialized = { admin: ReadonlyUint8Array; postFee: bigint }

export type BoardInitializedArgs = {
	admin: ReadonlyUint8Array
	postFee: number | bigint
}

export function getBoardInitializedEncoder(): FixedSizeEncoder<BoardInitializedArgs> {
	return getStructEncoder([
		["admin", fixEncoderSize(getBytesEncoder(), 32)],
		["postFee", getU64Encoder()]
	])
}

export function getBoardInitializedDecoder(): FixedSizeDecoder<BoardInitialized> {
	return getStructDecoder([
		["admin", fixDecoderSize(getBytesDecoder(), 32)],
		["postFee", getU64Decoder()]
	])
}

export function getBoardInitializedCodec(): FixedSizeCodec<BoardInitializedArgs, BoardInitialized> {
	return combineCodec(getBoardInitializedEncoder(), getBoardInitializedDecoder())
}
