/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

export * from "./boardEvent"
export * from "./boardInitialized"
export * from "./messageDeleted"
export * from "./messagePosted"
export * from "./postStatus"
export * from "./profileCreated"
export * from "./profileSuspended"
export * from "./usernameUpdated"
export * from "./userStatus"
