/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type Codec,
	combineCodec,
	type Decoder,
	type Encoder,
	fixDecoderSize,
	fixEncoderSize,
	getBytesDecoder,
	getBytesEncoder,
	getOptionDecoder,
	getOptionEncoder,
	getStructDecoder,
	getStructEncoder,
	getU32Decoder,
	getU32Encoder,
	type Option,
	type OptionOrNullable,
	type ReadonlyUint8Array
} from "@solana/kit"

export type MessagePosted = {
	author: ReadonlyUint8Array
	postIndex: number
	replyTo: Option<ReadonlyUint8Array>
}

export type MessagePostedArgs = {
	author: ReadonlyUint8Array
	postIndex: number
	replyTo: OptionOrNullable<ReadonlyUint8Array>
}

export function getMessagePostedEncoder(): Encoder<MessagePostedArgs> {
	return getStructEncoder([
		["author", fixEncoderSize(getBytesEncoder(), 32)],
		["postIndex", getU32Encoder()],
		["replyTo", getOptionEncoder(fixEncoderSize(getBytesEncoder(), 32))]
	])
}

export function getMessagePostedDecoder(): Decoder<MessagePosted> {
	return getStructDecoder([
		["author", fixDecoderSize(getBytesDecoder(), 32)],
		["postIndex", getU32Decoder()],
		["replyTo", getOptionDecoder(fixDecoderSize(getBytesDecoder(), 32))]
	])
}

export function getMessagePostedCodec(): Codec<MessagePostedArgs, MessagePosted> {
	return combineCodec(getMessagePostedEncoder(), getMessagePostedDecoder())
}
