/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	fixDecoderSize,
	fixEncoderSize,
	getBytesDecoder,
	getBytesEncoder,
	getStructDecoder,
	getStructEncoder,
	type ReadonlyUint8Array
} from "@solana/kit"

export type MessageDeleted = {
	post: ReadonlyUint8Array
	deletedBy: ReadonlyUint8Array
}

export type MessageDeletedArgs = MessageDeleted

export function getMessageDeletedEncoder(): FixedSizeEncoder<MessageDeletedArgs> {
	return getStructEncoder([
		["post", fixEncoderSize(getBytesEncoder(), 32)],
		["deletedBy", fixEncoderSize(getBytesEncoder(), 32)]
	])
}

export function getMessageDeletedDecoder(): FixedSizeDecoder<MessageDeleted> {
	return getStructDecoder([
		["post", fixDecoderSize(getBytesDecoder(), 32)],
		["deletedBy", fixDecoderSize(getBytesDecoder(), 32)]
	])
}

export function getMessageDeletedCodec(): FixedSizeCodec<MessageDeletedArgs, MessageDeleted> {
	return combineCodec(getMessageDeletedEncoder(), getMessageDeletedDecoder())
}
