/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	getEnumDecoder,
	getEnumEncoder
} from "@solana/kit"

export enum PostStatus {
	Published,
	Deleted
}

export type PostStatusArgs = PostStatus

export function getPostStatusEncoder(): FixedSizeEncoder<PostStatusArgs> {
	return getEnumEncoder(PostStatus)
}

export function getPostStatusDecoder(): FixedSizeDecoder<PostStatus> {
	return getEnumDecoder(PostStatus)
}

export function getPostStatusCodec(): FixedSizeCodec<PostStatusArgs, PostStatus> {
	return combineCodec(getPostStatusEncoder(), getPostStatusDecoder())
}
