/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	fixDecoderSize,
	fixEncoderSize,
	getBytesDecoder,
	getBytesEncoder,
	getStructDecoder,
	getStructEncoder,
	type ReadonlyUint8Array
} from "@solana/kit"

export type ProfileSuspended = { profileAuthority: ReadonlyUint8Array }

export type ProfileSuspendedArgs = ProfileSuspended

export function getProfileSuspendedEncoder(): FixedSizeEncoder<ProfileSuspendedArgs> {
	return getStructEncoder([["profileAuthority", fixEncoderSize(getBytesEncoder(), 32)]])
}

export function getProfileSuspendedDecoder(): FixedSizeDecoder<ProfileSuspended> {
	return getStructDecoder([["profileAuthority", fixDecoderSize(getBytesDecoder(), 32)]])
}

export function getProfileSuspendedCodec(): FixedSizeCodec<ProfileSuspendedArgs, ProfileSuspended> {
	return combineCodec(getProfileSuspendedEncoder(), getProfileSuspendedDecoder())
}
