/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	fixDecoderSize,
	fixEncoderSize,
	getBytesDecoder,
	getBytesEncoder,
	getStructDecoder,
	getStructEncoder,
	type ReadonlyUint8Array
} from "@solana/kit"

export type ProfileCreated = {
	authority: ReadonlyUint8Array
	username: ReadonlyUint8Array
}

export type ProfileCreatedArgs = ProfileCreated

export function getProfileCreatedEncoder(): FixedSizeEncoder<ProfileCreatedArgs> {
	return getStructEncoder([
		["authority", fixEncoderSize(getBytesEncoder(), 32)],
		["username", fixEncoderSize(getBytesEncoder(), 32)]
	])
}

export function getProfileCreatedDecoder(): FixedSizeDecoder<ProfileCreated> {
	return getStructDecoder([
		["authority", fixDecoderSize(getBytesDecoder(), 32)],
		["username", fixDecoderSize(getBytesDecoder(), 32)]
	])
}

export function getProfileCreatedCodec(): FixedSizeCodec<ProfileCreatedArgs, ProfileCreated> {
	return combineCodec(getProfileCreatedEncoder(), getProfileCreatedDecoder())
}
