/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	fixDecoderSize,
	fixEncoderSize,
	getBytesDecoder,
	getBytesEncoder,
	getStructDecoder,
	getStructEncoder,
	type ReadonlyUint8Array
} from "@solana/kit"

export type UsernameUpdated = {
	authority: ReadonlyUint8Array
	newUsername: ReadonlyUint8Array
}

export type UsernameUpdatedArgs = UsernameUpdated

export function getUsernameUpdatedEncoder(): FixedSizeEncoder<UsernameUpdatedArgs> {
	return getStructEncoder([
		["authority", fixEncoderSize(getBytesEncoder(), 32)],
		["newUsername", fixEncoderSize(getBytesEncoder(), 32)]
	])
}

export function getUsernameUpdatedDecoder(): FixedSizeDecoder<UsernameUpdated> {
	return getStructDecoder([
		["authority", fixDecoderSize(getBytesDecoder(), 32)],
		["newUsername", fixDecoderSize(getBytesDecoder(), 32)]
	])
}

export function getUsernameUpdatedCodec(): FixedSizeCodec<UsernameUpdatedArgs, UsernameUpdated> {
	return combineCodec(getUsernameUpdatedEncoder(), getUsernameUpdatedDecoder())
}
