[workspace]
resolver = "2"
members = ["basic/*", "shared", "token/*"]

[workspace.dependencies]
pinocchio = { git = "https://github.com/anza-xyz/pinocchio", package = "pinocchio" }
pinocchio-log = "0.5"
pinocchio-pubkey = "0.3"
pinocchio-system = { git = "https://github.com/anza-xyz/pinocchio", package = "pinocchio-system" }
pinocchio-token = { git = "https://github.com/anza-xyz/pinocchio", package = "pinocchio-token" }
pinocchio-token-2022 = { git = "https://github.com/anza-xyz/pinocchio", package = "pinocchio-token-2022" }
shank = "0.4"
borsh = { version = "1.6", features = ["derive"] }
base64 = "0.22"
