/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type Account,
	type Address,
	assertAccountExists,
	assertAccountsExist,
	combineCodec,
	decodeAccount,
	type EncodedAccount,
	type FetchAccountConfig,
	type FetchAccountsConfig,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	fetchEncodedAccount,
	fetchEncodedAccounts,
	fixDecoderSize,
	fixEncoderSize,
	getBooleanDecoder,
	getBooleanEncoder,
	getBytesDecoder,
	getBytesEncoder,
	getStructDecoder,
	getStructEncoder,
	getU8Decoder,
	getU8Encoder,
	getU64Decoder,
	getU64Encoder,
	type MaybeAccount,
	type MaybeEncodedAccount,
	type ReadonlyUint8Array
} from "@solana/kit"

export type BoardConfig = {
	admin: ReadonlyUint8Array
	postFee: bigint
	postCount: bigint
	isPaused: boolean
	bump: number
}

export type BoardConfigArgs = {
	admin: ReadonlyUint8Array
	postFee: number | bigint
	postCount: number | bigint
	isPaused: boolean
	bump: number
}

/** Gets the encoder for {@link BoardConfigArgs} account data. */
export function getBoardConfigEncoder(): FixedSizeEncoder<BoardConfigArgs> {
	return getStructEncoder([
		["admin", fixEncoderSize(getBytesEncoder(), 32)],
		["postFee", getU64Encoder()],
		["postCount", getU64Encoder()],
		["isPaused", getBooleanEncoder()],
		["bump", getU8Encoder()]
	])
}

/** Gets the decoder for {@link BoardConfig} account data. */
export function getBoardConfigDecoder(): FixedSizeDecoder<BoardConfig> {
	return getStructDecoder([
		["admin", fixDecoderSize(getBytesDecoder(), 32)],
		["postFee", getU64Decoder()],
		["postCount", getU64Decoder()],
		["isPaused", getBooleanDecoder()],
		["bump", getU8Decoder()]
	])
}

/** Gets the codec for {@link BoardConfig} account data. */
export function getBoardConfigCodec(): FixedSizeCodec<BoardConfigArgs, BoardConfig> {
	return combineCodec(getBoardConfigEncoder(), getBoardConfigDecoder())
}

export function decodeBoardConfig<TAddress extends string = string>(
	encodedAccount: EncodedAccount<TAddress>
): Account<BoardConfig, TAddress>
export function decodeBoardConfig<TAddress extends string = string>(
	encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<BoardConfig, TAddress>
export function decodeBoardConfig<TAddress extends string = string>(
	encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
): Account<BoardConfig, TAddress> | MaybeAccount<BoardConfig, TAddress> {
	return decodeAccount(encodedAccount as MaybeEncodedAccount<TAddress>, getBoardConfigDecoder())
}

export async function fetchBoardConfig<TAddress extends string = string>(
	rpc: Parameters<typeof fetchEncodedAccount>[0],
	address: Address<TAddress>,
	config?: FetchAccountConfig
): Promise<Account<BoardConfig, TAddress>> {
	const maybeAccount = await fetchMaybeBoardConfig(rpc, address, config)
	assertAccountExists(maybeAccount)
	return maybeAccount
}

export async function fetchMaybeBoardConfig<TAddress extends string = string>(
	rpc: Parameters<typeof fetchEncodedAccount>[0],
	address: Address<TAddress>,
	config?: FetchAccountConfig
): Promise<MaybeAccount<BoardConfig, TAddress>> {
	const maybeAccount = await fetchEncodedAccount(rpc, address, config)
	return decodeBoardConfig(maybeAccount)
}

export async function fetchAllBoardConfig(
	rpc: Parameters<typeof fetchEncodedAccounts>[0],
	addresses: Array<Address>,
	config?: FetchAccountsConfig
): Promise<Account<BoardConfig>[]> {
	const maybeAccounts = await fetchAllMaybeBoardConfig(rpc, addresses, config)
	assertAccountsExist(maybeAccounts)
	return maybeAccounts
}

export async function fetchAllMaybeBoardConfig(
	rpc: Parameters<typeof fetchEncodedAccounts>[0],
	addresses: Array<Address>,
	config?: FetchAccountsConfig
): Promise<MaybeAccount<BoardConfig>[]> {
	const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config)
	return maybeAccounts.map(maybeAccount => decodeBoardConfig(maybeAccount))
}

export function getBoardConfigSize(): number {
	return 50
}
