/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type Account,
	type Address,
	assertAccountExists,
	assertAccountsExist,
	type Codec,
	combineCodec,
	type Decoder,
	decodeAccount,
	type EncodedAccount,
	type Encoder,
	type FetchAccountConfig,
	type FetchAccountsConfig,
	fetchEncodedAccount,
	fetchEncodedAccounts,
	fixDecoderSize,
	fixEncoderSize,
	getBytesDecoder,
	getBytesEncoder,
	getOptionDecoder,
	getOptionEncoder,
	getStructDecoder,
	getStructEncoder,
	getU8Decoder,
	getU8Encoder,
	getU32Decoder,
	getU32Encoder,
	type MaybeAccount,
	type MaybeEncodedAccount,
	type Option,
	type OptionOrNullable,
	type ReadonlyUint8Array
} from "@solana/kit"
import {
	getPostStatusDecoder,
	getPostStatusEncoder,
	type PostStatus,
	type PostStatusArgs
} from "../types"

export type Post = {
	author: ReadonlyUint8Array
	content: ReadonlyUint8Array
	replyTo: Option<ReadonlyUint8Array>
	status: PostStatus
	postIndex: number
	bump: number
}

export type PostArgs = {
	author: ReadonlyUint8Array
	content: ReadonlyUint8Array
	replyTo: OptionOrNullable<ReadonlyUint8Array>
	status: PostStatusArgs
	postIndex: number
	bump: number
}

/** Gets the encoder for {@link PostArgs} account data. */
export function getPostEncoder(): Encoder<PostArgs> {
	return getStructEncoder([
		["author", fixEncoderSize(getBytesEncoder(), 32)],
		["content", fixEncoderSize(getBytesEncoder(), 128)],
		["replyTo", getOptionEncoder(fixEncoderSize(getBytesEncoder(), 32))],
		["status", getPostStatusEncoder()],
		["postIndex", getU32Encoder()],
		["bump", getU8Encoder()]
	])
}

/** Gets the decoder for {@link Post} account data. */
export function getPostDecoder(): Decoder<Post> {
	return getStructDecoder([
		["author", fixDecoderSize(getBytesDecoder(), 32)],
		["content", fixDecoderSize(getBytesDecoder(), 128)],
		["replyTo", getOptionDecoder(fixDecoderSize(getBytesDecoder(), 32))],
		["status", getPostStatusDecoder()],
		["postIndex", getU32Decoder()],
		["bump", getU8Decoder()]
	])
}

/** Gets the codec for {@link Post} account data. */
export function getPostCodec(): Codec<PostArgs, Post> {
	return combineCodec(getPostEncoder(), getPostDecoder())
}

export function decodePost<TAddress extends string = string>(
	encodedAccount: EncodedAccount<TAddress>
): Account<Post, TAddress>
export function decodePost<TAddress extends string = string>(
	encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<Post, TAddress>
export function decodePost<TAddress extends string = string>(
	encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
): Account<Post, TAddress> | MaybeAccount<Post, TAddress> {
	return decodeAccount(encodedAccount as MaybeEncodedAccount<TAddress>, getPostDecoder())
}

export async function fetchPost<TAddress extends string = string>(
	rpc: Parameters<typeof fetchEncodedAccount>[0],
	address: Address<TAddress>,
	config?: FetchAccountConfig
): Promise<Account<Post, TAddress>> {
	const maybeAccount = await fetchMaybePost(rpc, address, config)
	assertAccountExists(maybeAccount)
	return maybeAccount
}

export async function fetchMaybePost<TAddress extends string = string>(
	rpc: Parameters<typeof fetchEncodedAccount>[0],
	address: Address<TAddress>,
	config?: FetchAccountConfig
): Promise<MaybeAccount<Post, TAddress>> {
	const maybeAccount = await fetchEncodedAccount(rpc, address, config)
	return decodePost(maybeAccount)
}

export async function fetchAllPost(
	rpc: Parameters<typeof fetchEncodedAccounts>[0],
	addresses: Array<Address>,
	config?: FetchAccountsConfig
): Promise<Account<Post>[]> {
	const maybeAccounts = await fetchAllMaybePost(rpc, addresses, config)
	assertAccountsExist(maybeAccounts)
	return maybeAccounts
}

export async function fetchAllMaybePost(
	rpc: Parameters<typeof fetchEncodedAccounts>[0],
	addresses: Array<Address>,
	config?: FetchAccountsConfig
): Promise<MaybeAccount<Post>[]> {
	const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config)
	return maybeAccounts.map(maybeAccount => decodePost(maybeAccount))
}
