/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type Account,
	type Address,
	assertAccountExists,
	assertAccountsExist,
	combineCodec,
	decodeAccount,
	type EncodedAccount,
	type FetchAccountConfig,
	type FetchAccountsConfig,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	fetchEncodedAccount,
	fetchEncodedAccounts,
	fixDecoderSize,
	fixEncoderSize,
	getBytesDecoder,
	getBytesEncoder,
	getStructDecoder,
	getStructEncoder,
	getU8Decoder,
	getU8Encoder,
	getU32Decoder,
	getU32Encoder,
	type MaybeAccount,
	type MaybeEncodedAccount,
	type ReadonlyUint8Array
} from "@solana/kit"
import {
	getUserStatusDecoder,
	getUserStatusEncoder,
	type UserStatus,
	type UserStatusArgs
} from "../types"

export type UserProfile = {
	authority: ReadonlyUint8Array
	username: ReadonlyUint8Array
	postCount: number
	status: UserStatus
	bump: number
}

export type UserProfileArgs = {
	authority: ReadonlyUint8Array
	username: ReadonlyUint8Array
	postCount: number
	status: UserStatusArgs
	bump: number
}

/** Gets the encoder for {@link UserProfileArgs} account data. */
export function getUserProfileEncoder(): FixedSizeEncoder<UserProfileArgs> {
	return getStructEncoder([
		["authority", fixEncoderSize(getBytesEncoder(), 32)],
		["username", fixEncoderSize(getBytesEncoder(), 32)],
		["postCount", getU32Encoder()],
		["status", getUserStatusEncoder()],
		["bump", getU8Encoder()]
	])
}

/** Gets the decoder for {@link UserProfile} account data. */
export function getUserProfileDecoder(): FixedSizeDecoder<UserProfile> {
	return getStructDecoder([
		["authority", fixDecoderSize(getBytesDecoder(), 32)],
		["username", fixDecoderSize(getBytesDecoder(), 32)],
		["postCount", getU32Decoder()],
		["status", getUserStatusDecoder()],
		["bump", getU8Decoder()]
	])
}

/** Gets the codec for {@link UserProfile} account data. */
export function getUserProfileCodec(): FixedSizeCodec<UserProfileArgs, UserProfile> {
	return combineCodec(getUserProfileEncoder(), getUserProfileDecoder())
}

export function decodeUserProfile<TAddress extends string = string>(
	encodedAccount: EncodedAccount<TAddress>
): Account<UserProfile, TAddress>
export function decodeUserProfile<TAddress extends string = string>(
	encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<UserProfile, TAddress>
export function decodeUserProfile<TAddress extends string = string>(
	encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
): Account<UserProfile, TAddress> | MaybeAccount<UserProfile, TAddress> {
	return decodeAccount(encodedAccount as MaybeEncodedAccount<TAddress>, getUserProfileDecoder())
}

export async function fetchUserProfile<TAddress extends string = string>(
	rpc: Parameters<typeof fetchEncodedAccount>[0],
	address: Address<TAddress>,
	config?: FetchAccountConfig
): Promise<Account<UserProfile, TAddress>> {
	const maybeAccount = await fetchMaybeUserProfile(rpc, address, config)
	assertAccountExists(maybeAccount)
	return maybeAccount
}

export async function fetchMaybeUserProfile<TAddress extends string = string>(
	rpc: Parameters<typeof fetchEncodedAccount>[0],
	address: Address<TAddress>,
	config?: FetchAccountConfig
): Promise<MaybeAccount<UserProfile, TAddress>> {
	const maybeAccount = await fetchEncodedAccount(rpc, address, config)
	return decodeUserProfile(maybeAccount)
}

export async function fetchAllUserProfile(
	rpc: Parameters<typeof fetchEncodedAccounts>[0],
	addresses: Array<Address>,
	config?: FetchAccountsConfig
): Promise<Account<UserProfile>[]> {
	const maybeAccounts = await fetchAllMaybeUserProfile(rpc, addresses, config)
	assertAccountsExist(maybeAccounts)
	return maybeAccounts
}

export async function fetchAllMaybeUserProfile(
	rpc: Parameters<typeof fetchEncodedAccounts>[0],
	addresses: Array<Address>,
	config?: FetchAccountsConfig
): Promise<MaybeAccount<UserProfile>[]> {
	const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config)
	return maybeAccounts.map(maybeAccount => decodeUserProfile(maybeAccount))
}

export function getUserProfileSize(): number {
	return 70
}
