/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type Address,
	assertIsInstructionWithAccounts,
	type ClientWithRpc,
	type ClientWithTransactionPlanning,
	type ClientWithTransactionSending,
	containsBytes,
	type GetAccountInfoApi,
	type GetMultipleAccountsApi,
	getU8Encoder,
	type Instruction,
	type InstructionWithData,
	type ReadonlyUint8Array,
	SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_INSTRUCTION,
	SOLANA_ERROR__PROGRAM_CLIENTS__UNRECOGNIZED_INSTRUCTION_TYPE,
	SolanaError
} from "@solana/kit"
import {
	addSelfFetchFunctions,
	addSelfPlanAndSendFunctions,
	type SelfFetchFunctions,
	type SelfPlanAndSendFunctions
} from "@solana/program-client-core"
import { getVaultCodec, type Vault, type VaultArgs } from "../accounts"
import {
	type CreateVaultInput,
	getCreateVaultInstruction,
	getSwapExactInInstruction,
	getSwapExactOutInstruction,
	type ParsedCreateVaultInstruction,
	type ParsedSwapExactInInstruction,
	type ParsedSwapExactOutInstruction,
	parseCreateVaultInstruction,
	parseSwapExactInInstruction,
	parseSwapExactOutInstruction,
	type SwapExactInInput,
	type SwapExactOutInput
} from "../instructions"

export const VAULT_PROGRAM_ADDRESS =
	"9pq4Z25ahsUMFZ9TrKH1yhmibLbGkxxAdbTn7FUJ7reV" as Address<"9pq4Z25ahsUMFZ9TrKH1yhmibLbGkxxAdbTn7FUJ7reV">

export enum VaultAccount {
	Vault
}

export enum VaultInstruction {
	CreateVault,
	SwapExactIn,
	SwapExactOut
}

export function identifyVaultInstruction(
	instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): VaultInstruction {
	const data = "data" in instruction ? instruction.data : instruction
	if (containsBytes(data, getU8Encoder().encode(0), 0)) {
		return VaultInstruction.CreateVault
	}
	if (containsBytes(data, getU8Encoder().encode(1), 0)) {
		return VaultInstruction.SwapExactIn
	}
	if (containsBytes(data, getU8Encoder().encode(2), 0)) {
		return VaultInstruction.SwapExactOut
	}
	throw new SolanaError(SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_INSTRUCTION, {
		instructionData: data,
		programName: "vault"
	})
}

export type ParsedVaultInstruction<
	TProgram extends string = "9pq4Z25ahsUMFZ9TrKH1yhmibLbGkxxAdbTn7FUJ7reV"
> =
	| ({
			instructionType: VaultInstruction.CreateVault
	  } & ParsedCreateVaultInstruction<TProgram>)
	| ({
			instructionType: VaultInstruction.SwapExactIn
	  } & ParsedSwapExactInInstruction<TProgram>)
	| ({
			instructionType: VaultInstruction.SwapExactOut
	  } & ParsedSwapExactOutInstruction<TProgram>)

export function parseVaultInstruction<TProgram extends string>(
	instruction: Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array>
): ParsedVaultInstruction<TProgram> {
	const instructionType = identifyVaultInstruction(instruction)
	switch (instructionType) {
		case VaultInstruction.CreateVault: {
			assertIsInstructionWithAccounts(instruction)
			return {
				instructionType: VaultInstruction.CreateVault,
				...parseCreateVaultInstruction(instruction)
			}
		}
		case VaultInstruction.SwapExactIn: {
			assertIsInstructionWithAccounts(instruction)
			return {
				instructionType: VaultInstruction.SwapExactIn,
				...parseSwapExactInInstruction(instruction)
			}
		}
		case VaultInstruction.SwapExactOut: {
			assertIsInstructionWithAccounts(instruction)
			return {
				instructionType: VaultInstruction.SwapExactOut,
				...parseSwapExactOutInstruction(instruction)
			}
		}
		default:
			throw new SolanaError(SOLANA_ERROR__PROGRAM_CLIENTS__UNRECOGNIZED_INSTRUCTION_TYPE, {
				instructionType: instructionType as string,
				programName: "vault"
			})
	}
}

export type VaultPlugin = {
	accounts: VaultPluginAccounts
	instructions: VaultPluginInstructions
}

export type VaultPluginAccounts = {
	vault: ReturnType<typeof getVaultCodec> & SelfFetchFunctions<VaultArgs, Vault>
}

export type VaultPluginInstructions = {
	createVault: (
		input: CreateVaultInput
	) => ReturnType<typeof getCreateVaultInstruction> & SelfPlanAndSendFunctions
	swapExactIn: (
		input: SwapExactInInput
	) => ReturnType<typeof getSwapExactInInstruction> & SelfPlanAndSendFunctions
	swapExactOut: (
		input: SwapExactOutInput
	) => ReturnType<typeof getSwapExactOutInstruction> & SelfPlanAndSendFunctions
}

export type VaultPluginRequirements = ClientWithRpc<GetAccountInfoApi & GetMultipleAccountsApi> &
	ClientWithTransactionPlanning &
	ClientWithTransactionSending

export function vaultProgram() {
	return <T extends VaultPluginRequirements>(client: T) => {
		return {
			...client,
			vault: <VaultPlugin>{
				accounts: { vault: addSelfFetchFunctions(client, getVaultCodec()) },
				instructions: {
					createVault: input =>
						addSelfPlanAndSendFunctions(client, getCreateVaultInstruction(input)),
					swapExactIn: input =>
						addSelfPlanAndSendFunctions(client, getSwapExactInInstruction(input)),
					swapExactOut: input =>
						addSelfPlanAndSendFunctions(client, getSwapExactOutInstruction(input))
				}
			}
		}
	}
}
