/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { type Address, containsBytes, getU8Encoder, type ReadonlyUint8Array } from "@solana/kit"
import type { ParsedCloseMemeInstruction, ParsedCreateMemeInstruction } from "../instructions"

export const CLOSE_ACCOUNT_PROGRAM_ADDRESS =
	"2HXWQuEjgRDbNcMx3X32C1aw4fftVMHyUf9KXYyTiPiD" as Address<"2HXWQuEjgRDbNcMx3X32C1aw4fftVMHyUf9KXYyTiPiD">

export enum CloseAccountAccount {
	Meme
}

export enum CloseAccountInstruction {
	CreateMeme,
	CloseMeme
}

export function identifyCloseAccountInstruction(
	instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): CloseAccountInstruction {
	const data = "data" in instruction ? instruction.data : instruction
	if (containsBytes(data, getU8Encoder().encode(0), 0)) {
		return CloseAccountInstruction.CreateMeme
	}
	if (containsBytes(data, getU8Encoder().encode(1), 0)) {
		return CloseAccountInstruction.CloseMeme
	}
	throw new Error("The provided instruction could not be identified as a closeAccount instruction.")
}

export type ParsedCloseAccountInstruction<
	TProgram extends string = "2HXWQuEjgRDbNcMx3X32C1aw4fftVMHyUf9KXYyTiPiD"
> =
	| ({
			instructionType: CloseAccountInstruction.CreateMeme
	  } & ParsedCreateMemeInstruction<TProgram>)
	| ({
			instructionType: CloseAccountInstruction.CloseMeme
	  } & ParsedCloseMemeInstruction<TProgram>)
