/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type AccountMeta,
	type AccountSignerMeta,
	type Address,
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	fixDecoderSize,
	fixEncoderSize,
	getBytesDecoder,
	getBytesEncoder,
	getStructDecoder,
	getStructEncoder,
	getU8Decoder,
	getU8Encoder,
	getU64Decoder,
	getU64Encoder,
	type Instruction,
	type InstructionWithAccounts,
	type InstructionWithData,
	type ReadonlyAccount,
	type ReadonlySignerAccount,
	type ReadonlyUint8Array,
	SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
	SolanaError,
	type TransactionSigner,
	transformEncoder,
	type WritableAccount
} from "@solana/kit"
import { getAccountMetaFactory, type ResolvedInstructionAccount } from "@solana/program-client-core"
import { VAULT_PROGRAM_ADDRESS } from "../programs"

export const CREATE_VAULT_DISCRIMINATOR = 0

export function getCreateVaultDiscriminatorBytes() {
	return getU8Encoder().encode(CREATE_VAULT_DISCRIMINATOR)
}

export type CreateVaultInstruction<
	TProgram extends string = typeof VAULT_PROGRAM_ADDRESS,
	TAccountOwner extends string | AccountMeta<string> = string,
	TAccountVault extends string | AccountMeta<string> = string,
	TAccountUserTokenAccountA extends string | AccountMeta<string> = string,
	TAccountUserTokenAccountB extends string | AccountMeta<string> = string,
	TAccountVaultTokenAccountA extends string | AccountMeta<string> = string,
	TAccountVaultTokenAccountB extends string | AccountMeta<string> = string,
	TAccountTokenProgramA extends string | AccountMeta<string> = string,
	TAccountTokenProgramB extends string | AccountMeta<string> = string,
	TAccountSystemProgram extends string | AccountMeta<string> = "11111111111111111111111111111111",
	TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
	InstructionWithData<ReadonlyUint8Array> &
	InstructionWithAccounts<
		[
			TAccountOwner extends string
				? ReadonlySignerAccount<TAccountOwner> & AccountSignerMeta<TAccountOwner>
				: TAccountOwner,
			TAccountVault extends string ? WritableAccount<TAccountVault> : TAccountVault,
			TAccountUserTokenAccountA extends string
				? WritableAccount<TAccountUserTokenAccountA>
				: TAccountUserTokenAccountA,
			TAccountUserTokenAccountB extends string
				? WritableAccount<TAccountUserTokenAccountB>
				: TAccountUserTokenAccountB,
			TAccountVaultTokenAccountA extends string
				? WritableAccount<TAccountVaultTokenAccountA>
				: TAccountVaultTokenAccountA,
			TAccountVaultTokenAccountB extends string
				? WritableAccount<TAccountVaultTokenAccountB>
				: TAccountVaultTokenAccountB,
			TAccountTokenProgramA extends string
				? ReadonlyAccount<TAccountTokenProgramA>
				: TAccountTokenProgramA,
			TAccountTokenProgramB extends string
				? ReadonlyAccount<TAccountTokenProgramB>
				: TAccountTokenProgramB,
			TAccountSystemProgram extends string
				? ReadonlyAccount<TAccountSystemProgram>
				: TAccountSystemProgram,
			...TRemainingAccounts
		]
	>

export type CreateVaultInstructionData = {
	discriminator: number
	vaultId: ReadonlyUint8Array
	tokenMintA: ReadonlyUint8Array
	tokenMintB: ReadonlyUint8Array
	amountA: bigint
	amountB: bigint
}

export type CreateVaultInstructionDataArgs = {
	vaultId: ReadonlyUint8Array
	tokenMintA: ReadonlyUint8Array
	tokenMintB: ReadonlyUint8Array
	amountA: number | bigint
	amountB: number | bigint
}

export function getCreateVaultInstructionDataEncoder(): FixedSizeEncoder<CreateVaultInstructionDataArgs> {
	return transformEncoder(
		getStructEncoder([
			["discriminator", getU8Encoder()],
			["vaultId", fixEncoderSize(getBytesEncoder(), 32)],
			["tokenMintA", fixEncoderSize(getBytesEncoder(), 32)],
			["tokenMintB", fixEncoderSize(getBytesEncoder(), 32)],
			["amountA", getU64Encoder()],
			["amountB", getU64Encoder()]
		]),
		value => ({ ...value, discriminator: CREATE_VAULT_DISCRIMINATOR })
	)
}

export function getCreateVaultInstructionDataDecoder(): FixedSizeDecoder<CreateVaultInstructionData> {
	return getStructDecoder([
		["discriminator", getU8Decoder()],
		["vaultId", fixDecoderSize(getBytesDecoder(), 32)],
		["tokenMintA", fixDecoderSize(getBytesDecoder(), 32)],
		["tokenMintB", fixDecoderSize(getBytesDecoder(), 32)],
		["amountA", getU64Decoder()],
		["amountB", getU64Decoder()]
	])
}

export function getCreateVaultInstructionDataCodec(): FixedSizeCodec<
	CreateVaultInstructionDataArgs,
	CreateVaultInstructionData
> {
	return combineCodec(
		getCreateVaultInstructionDataEncoder(),
		getCreateVaultInstructionDataDecoder()
	)
}

export type CreateVaultInput<
	TAccountOwner extends string = string,
	TAccountVault extends string = string,
	TAccountUserTokenAccountA extends string = string,
	TAccountUserTokenAccountB extends string = string,
	TAccountVaultTokenAccountA extends string = string,
	TAccountVaultTokenAccountB extends string = string,
	TAccountTokenProgramA extends string = string,
	TAccountTokenProgramB extends string = string,
	TAccountSystemProgram extends string = string
> = {
	/** Vault owner; pays for account creation and provides initial liquidity */
	owner: TransactionSigner<TAccountOwner>
	/** Vault PDA (seeds: ['vault', owner, vault_id]) */
	vault: Address<TAccountVault>
	/** Owner's token A account */
	userTokenAccountA: Address<TAccountUserTokenAccountA>
	/** Owner's token B account */
	userTokenAccountB: Address<TAccountUserTokenAccountB>
	/** Vault's token A account (authority = vault PDA) */
	vaultTokenAccountA: Address<TAccountVaultTokenAccountA>
	/** Vault's token B account (authority = vault PDA) */
	vaultTokenAccountB: Address<TAccountVaultTokenAccountB>
	/** SPL Token or Token-2022 program for mint A */
	tokenProgramA: Address<TAccountTokenProgramA>
	/** SPL Token or Token-2022 program for mint B */
	tokenProgramB: Address<TAccountTokenProgramB>
	/** System program */
	systemProgram?: Address<TAccountSystemProgram>
	vaultId: CreateVaultInstructionDataArgs["vaultId"]
	tokenMintA: CreateVaultInstructionDataArgs["tokenMintA"]
	tokenMintB: CreateVaultInstructionDataArgs["tokenMintB"]
	amountA: CreateVaultInstructionDataArgs["amountA"]
	amountB: CreateVaultInstructionDataArgs["amountB"]
}

export function getCreateVaultInstruction<
	TAccountOwner extends string,
	TAccountVault extends string,
	TAccountUserTokenAccountA extends string,
	TAccountUserTokenAccountB extends string,
	TAccountVaultTokenAccountA extends string,
	TAccountVaultTokenAccountB extends string,
	TAccountTokenProgramA extends string,
	TAccountTokenProgramB extends string,
	TAccountSystemProgram extends string,
	TProgramAddress extends Address = typeof VAULT_PROGRAM_ADDRESS
>(
	input: CreateVaultInput<
		TAccountOwner,
		TAccountVault,
		TAccountUserTokenAccountA,
		TAccountUserTokenAccountB,
		TAccountVaultTokenAccountA,
		TAccountVaultTokenAccountB,
		TAccountTokenProgramA,
		TAccountTokenProgramB,
		TAccountSystemProgram
	>,
	config?: { programAddress?: TProgramAddress }
): CreateVaultInstruction<
	TProgramAddress,
	TAccountOwner,
	TAccountVault,
	TAccountUserTokenAccountA,
	TAccountUserTokenAccountB,
	TAccountVaultTokenAccountA,
	TAccountVaultTokenAccountB,
	TAccountTokenProgramA,
	TAccountTokenProgramB,
	TAccountSystemProgram
> {
	// Program address.
	const programAddress = config?.programAddress ?? VAULT_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		owner: { value: input.owner ?? null, isWritable: false },
		vault: { value: input.vault ?? null, isWritable: true },
		userTokenAccountA: {
			value: input.userTokenAccountA ?? null,
			isWritable: true
		},
		userTokenAccountB: {
			value: input.userTokenAccountB ?? null,
			isWritable: true
		},
		vaultTokenAccountA: {
			value: input.vaultTokenAccountA ?? null,
			isWritable: true
		},
		vaultTokenAccountB: {
			value: input.vaultTokenAccountB ?? null,
			isWritable: true
		},
		tokenProgramA: { value: input.tokenProgramA ?? null, isWritable: false },
		tokenProgramB: { value: input.tokenProgramB ?? null, isWritable: false },
		systemProgram: { value: input.systemProgram ?? null, isWritable: false }
	}
	const accounts = originalAccounts as Record<
		keyof typeof originalAccounts,
		ResolvedInstructionAccount
	>

	// Original args.
	const args = { ...input }

	// Resolve default values.
	if (!accounts.systemProgram.value) {
		accounts.systemProgram.value =
			"11111111111111111111111111111111" as Address<"11111111111111111111111111111111">
	}

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta("owner", accounts.owner),
			getAccountMeta("vault", accounts.vault),
			getAccountMeta("userTokenAccountA", accounts.userTokenAccountA),
			getAccountMeta("userTokenAccountB", accounts.userTokenAccountB),
			getAccountMeta("vaultTokenAccountA", accounts.vaultTokenAccountA),
			getAccountMeta("vaultTokenAccountB", accounts.vaultTokenAccountB),
			getAccountMeta("tokenProgramA", accounts.tokenProgramA),
			getAccountMeta("tokenProgramB", accounts.tokenProgramB),
			getAccountMeta("systemProgram", accounts.systemProgram)
		],
		data: getCreateVaultInstructionDataEncoder().encode(args as CreateVaultInstructionDataArgs),
		programAddress
	} as CreateVaultInstruction<
		TProgramAddress,
		TAccountOwner,
		TAccountVault,
		TAccountUserTokenAccountA,
		TAccountUserTokenAccountB,
		TAccountVaultTokenAccountA,
		TAccountVaultTokenAccountB,
		TAccountTokenProgramA,
		TAccountTokenProgramB,
		TAccountSystemProgram
	>)
}

export type ParsedCreateVaultInstruction<
	TProgram extends string = typeof VAULT_PROGRAM_ADDRESS,
	TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
	programAddress: Address<TProgram>
	accounts: {
		/** Vault owner; pays for account creation and provides initial liquidity */
		owner: TAccountMetas[0]
		/** Vault PDA (seeds: ['vault', owner, vault_id]) */
		vault: TAccountMetas[1]
		/** Owner's token A account */
		userTokenAccountA: TAccountMetas[2]
		/** Owner's token B account */
		userTokenAccountB: TAccountMetas[3]
		/** Vault's token A account (authority = vault PDA) */
		vaultTokenAccountA: TAccountMetas[4]
		/** Vault's token B account (authority = vault PDA) */
		vaultTokenAccountB: TAccountMetas[5]
		/** SPL Token or Token-2022 program for mint A */
		tokenProgramA: TAccountMetas[6]
		/** SPL Token or Token-2022 program for mint B */
		tokenProgramB: TAccountMetas[7]
		/** System program */
		systemProgram: TAccountMetas[8]
	}
	data: CreateVaultInstructionData
}

export function parseCreateVaultInstruction<
	TProgram extends string,
	TAccountMetas extends readonly AccountMeta[]
>(
	instruction: Instruction<TProgram> &
		InstructionWithAccounts<TAccountMetas> &
		InstructionWithData<ReadonlyUint8Array>
): ParsedCreateVaultInstruction<TProgram, TAccountMetas> {
	if (instruction.accounts.length < 9) {
		throw new SolanaError(SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS, {
			actualAccountMetas: instruction.accounts.length,
			expectedAccountMetas: 9
		})
	}
	let accountIndex = 0
	const getNextAccount = () => {
		const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!
		accountIndex += 1
		return accountMeta
	}
	return {
		programAddress: instruction.programAddress,
		accounts: {
			owner: getNextAccount(),
			vault: getNextAccount(),
			userTokenAccountA: getNextAccount(),
			userTokenAccountB: getNextAccount(),
			vaultTokenAccountA: getNextAccount(),
			vaultTokenAccountB: getNextAccount(),
			tokenProgramA: getNextAccount(),
			tokenProgramB: getNextAccount(),
			systemProgram: getNextAccount()
		},
		data: getCreateVaultInstructionDataDecoder().decode(instruction.data)
	}
}
