/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type AccountMeta,
	type AccountSignerMeta,
	type Address,
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	getStructDecoder,
	getStructEncoder,
	getU8Decoder,
	getU8Encoder,
	getU64Decoder,
	getU64Encoder,
	type Instruction,
	type InstructionWithAccounts,
	type InstructionWithData,
	type ReadonlyAccount,
	type ReadonlySignerAccount,
	type ReadonlyUint8Array,
	SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
	SolanaError,
	type TransactionSigner,
	transformEncoder,
	type WritableAccount
} from "@solana/kit"
import { getAccountMetaFactory, type ResolvedInstructionAccount } from "@solana/program-client-core"
import { VAULT_PROGRAM_ADDRESS } from "../programs"

export const SWAP_EXACT_OUT_DISCRIMINATOR = 2

export function getSwapExactOutDiscriminatorBytes() {
	return getU8Encoder().encode(SWAP_EXACT_OUT_DISCRIMINATOR)
}

export type SwapExactOutInstruction<
	TProgram extends string = typeof VAULT_PROGRAM_ADDRESS,
	TAccountUser extends string | AccountMeta<string> = string,
	TAccountVault extends string | AccountMeta<string> = string,
	TAccountUserTokenIn extends string | AccountMeta<string> = string,
	TAccountVaultTokenIn extends string | AccountMeta<string> = string,
	TAccountUserTokenOut extends string | AccountMeta<string> = string,
	TAccountVaultTokenOut extends string | AccountMeta<string> = string,
	TAccountTokenProgramIn extends string | AccountMeta<string> = string,
	TAccountTokenProgramOut extends string | AccountMeta<string> = string,
	TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
	InstructionWithData<ReadonlyUint8Array> &
	InstructionWithAccounts<
		[
			TAccountUser extends string
				? ReadonlySignerAccount<TAccountUser> & AccountSignerMeta<TAccountUser>
				: TAccountUser,
			TAccountVault extends string ? WritableAccount<TAccountVault> : TAccountVault,
			TAccountUserTokenIn extends string
				? WritableAccount<TAccountUserTokenIn>
				: TAccountUserTokenIn,
			TAccountVaultTokenIn extends string
				? WritableAccount<TAccountVaultTokenIn>
				: TAccountVaultTokenIn,
			TAccountUserTokenOut extends string
				? WritableAccount<TAccountUserTokenOut>
				: TAccountUserTokenOut,
			TAccountVaultTokenOut extends string
				? WritableAccount<TAccountVaultTokenOut>
				: TAccountVaultTokenOut,
			TAccountTokenProgramIn extends string
				? ReadonlyAccount<TAccountTokenProgramIn>
				: TAccountTokenProgramIn,
			TAccountTokenProgramOut extends string
				? ReadonlyAccount<TAccountTokenProgramOut>
				: TAccountTokenProgramOut,
			...TRemainingAccounts
		]
	>

export type SwapExactOutInstructionData = {
	discriminator: number
	amountOut: bigint
	maxAmountIn: bigint
}

export type SwapExactOutInstructionDataArgs = {
	amountOut: number | bigint
	maxAmountIn: number | bigint
}

export function getSwapExactOutInstructionDataEncoder(): FixedSizeEncoder<SwapExactOutInstructionDataArgs> {
	return transformEncoder(
		getStructEncoder([
			["discriminator", getU8Encoder()],
			["amountOut", getU64Encoder()],
			["maxAmountIn", getU64Encoder()]
		]),
		value => ({ ...value, discriminator: SWAP_EXACT_OUT_DISCRIMINATOR })
	)
}

export function getSwapExactOutInstructionDataDecoder(): FixedSizeDecoder<SwapExactOutInstructionData> {
	return getStructDecoder([
		["discriminator", getU8Decoder()],
		["amountOut", getU64Decoder()],
		["maxAmountIn", getU64Decoder()]
	])
}

export function getSwapExactOutInstructionDataCodec(): FixedSizeCodec<
	SwapExactOutInstructionDataArgs,
	SwapExactOutInstructionData
> {
	return combineCodec(
		getSwapExactOutInstructionDataEncoder(),
		getSwapExactOutInstructionDataDecoder()
	)
}

export type SwapExactOutInput<
	TAccountUser extends string = string,
	TAccountVault extends string = string,
	TAccountUserTokenIn extends string = string,
	TAccountVaultTokenIn extends string = string,
	TAccountUserTokenOut extends string = string,
	TAccountVaultTokenOut extends string = string,
	TAccountTokenProgramIn extends string = string,
	TAccountTokenProgramOut extends string = string
> = {
	/** Signer and authority of user token accounts */
	user: TransactionSigner<TAccountUser>
	/** Vault PDA */
	vault: Address<TAccountVault>
	/** User's source token account */
	userTokenIn: Address<TAccountUserTokenIn>
	/** Vault's matching source token account */
	vaultTokenIn: Address<TAccountVaultTokenIn>
	/** User's destination token account */
	userTokenOut: Address<TAccountUserTokenOut>
	/** Vault's matching destination token account */
	vaultTokenOut: Address<TAccountVaultTokenOut>
	/** SPL Token or Token-2022 program for the input token */
	tokenProgramIn: Address<TAccountTokenProgramIn>
	/** SPL Token or Token-2022 program for the output token */
	tokenProgramOut: Address<TAccountTokenProgramOut>
	amountOut: SwapExactOutInstructionDataArgs["amountOut"]
	maxAmountIn: SwapExactOutInstructionDataArgs["maxAmountIn"]
}

export function getSwapExactOutInstruction<
	TAccountUser extends string,
	TAccountVault extends string,
	TAccountUserTokenIn extends string,
	TAccountVaultTokenIn extends string,
	TAccountUserTokenOut extends string,
	TAccountVaultTokenOut extends string,
	TAccountTokenProgramIn extends string,
	TAccountTokenProgramOut extends string,
	TProgramAddress extends Address = typeof VAULT_PROGRAM_ADDRESS
>(
	input: SwapExactOutInput<
		TAccountUser,
		TAccountVault,
		TAccountUserTokenIn,
		TAccountVaultTokenIn,
		TAccountUserTokenOut,
		TAccountVaultTokenOut,
		TAccountTokenProgramIn,
		TAccountTokenProgramOut
	>,
	config?: { programAddress?: TProgramAddress }
): SwapExactOutInstruction<
	TProgramAddress,
	TAccountUser,
	TAccountVault,
	TAccountUserTokenIn,
	TAccountVaultTokenIn,
	TAccountUserTokenOut,
	TAccountVaultTokenOut,
	TAccountTokenProgramIn,
	TAccountTokenProgramOut
> {
	// Program address.
	const programAddress = config?.programAddress ?? VAULT_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		user: { value: input.user ?? null, isWritable: false },
		vault: { value: input.vault ?? null, isWritable: true },
		userTokenIn: { value: input.userTokenIn ?? null, isWritable: true },
		vaultTokenIn: { value: input.vaultTokenIn ?? null, isWritable: true },
		userTokenOut: { value: input.userTokenOut ?? null, isWritable: true },
		vaultTokenOut: { value: input.vaultTokenOut ?? null, isWritable: true },
		tokenProgramIn: { value: input.tokenProgramIn ?? null, isWritable: false },
		tokenProgramOut: {
			value: input.tokenProgramOut ?? null,
			isWritable: false
		}
	}
	const accounts = originalAccounts as Record<
		keyof typeof originalAccounts,
		ResolvedInstructionAccount
	>

	// Original args.
	const args = { ...input }

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta("user", accounts.user),
			getAccountMeta("vault", accounts.vault),
			getAccountMeta("userTokenIn", accounts.userTokenIn),
			getAccountMeta("vaultTokenIn", accounts.vaultTokenIn),
			getAccountMeta("userTokenOut", accounts.userTokenOut),
			getAccountMeta("vaultTokenOut", accounts.vaultTokenOut),
			getAccountMeta("tokenProgramIn", accounts.tokenProgramIn),
			getAccountMeta("tokenProgramOut", accounts.tokenProgramOut)
		],
		data: getSwapExactOutInstructionDataEncoder().encode(args as SwapExactOutInstructionDataArgs),
		programAddress
	} as SwapExactOutInstruction<
		TProgramAddress,
		TAccountUser,
		TAccountVault,
		TAccountUserTokenIn,
		TAccountVaultTokenIn,
		TAccountUserTokenOut,
		TAccountVaultTokenOut,
		TAccountTokenProgramIn,
		TAccountTokenProgramOut
	>)
}

export type ParsedSwapExactOutInstruction<
	TProgram extends string = typeof VAULT_PROGRAM_ADDRESS,
	TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
	programAddress: Address<TProgram>
	accounts: {
		/** Signer and authority of user token accounts */
		user: TAccountMetas[0]
		/** Vault PDA */
		vault: TAccountMetas[1]
		/** User's source token account */
		userTokenIn: TAccountMetas[2]
		/** Vault's matching source token account */
		vaultTokenIn: TAccountMetas[3]
		/** User's destination token account */
		userTokenOut: TAccountMetas[4]
		/** Vault's matching destination token account */
		vaultTokenOut: TAccountMetas[5]
		/** SPL Token or Token-2022 program for the input token */
		tokenProgramIn: TAccountMetas[6]
		/** SPL Token or Token-2022 program for the output token */
		tokenProgramOut: TAccountMetas[7]
	}
	data: SwapExactOutInstructionData
}

export function parseSwapExactOutInstruction<
	TProgram extends string,
	TAccountMetas extends readonly AccountMeta[]
>(
	instruction: Instruction<TProgram> &
		InstructionWithAccounts<TAccountMetas> &
		InstructionWithData<ReadonlyUint8Array>
): ParsedSwapExactOutInstruction<TProgram, TAccountMetas> {
	if (instruction.accounts.length < 8) {
		throw new SolanaError(SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS, {
			actualAccountMetas: instruction.accounts.length,
			expectedAccountMetas: 8
		})
	}
	let accountIndex = 0
	const getNextAccount = () => {
		const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!
		accountIndex += 1
		return accountMeta
	}
	return {
		programAddress: instruction.programAddress,
		accounts: {
			user: getNextAccount(),
			vault: getNextAccount(),
			userTokenIn: getNextAccount(),
			vaultTokenIn: getNextAccount(),
			userTokenOut: getNextAccount(),
			vaultTokenOut: getNextAccount(),
			tokenProgramIn: getNextAccount(),
			tokenProgramOut: getNextAccount()
		},
		data: getSwapExactOutInstructionDataDecoder().decode(instruction.data)
	}
}
