/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type Account,
	type Address,
	assertAccountExists,
	assertAccountsExist,
	combineCodec,
	decodeAccount,
	type EncodedAccount,
	type FetchAccountConfig,
	type FetchAccountsConfig,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	fetchEncodedAccount,
	fetchEncodedAccounts,
	fixDecoderSize,
	fixEncoderSize,
	getBytesDecoder,
	getBytesEncoder,
	getStructDecoder,
	getStructEncoder,
	getU8Decoder,
	getU8Encoder,
	getU64Decoder,
	getU64Encoder,
	getU128Decoder,
	getU128Encoder,
	type MaybeAccount,
	type MaybeEncodedAccount,
	type ReadonlyUint8Array
} from "@solana/kit"

export type Vault = {
	owner: ReadonlyUint8Array
	vaultId: ReadonlyUint8Array
	tokenMintA: ReadonlyUint8Array
	tokenMintB: ReadonlyUint8Array
	tokenAccountA: ReadonlyUint8Array
	tokenAccountB: ReadonlyUint8Array
	tokenProgramA: ReadonlyUint8Array
	tokenProgramB: ReadonlyUint8Array
	reserveA: bigint
	reserveB: bigint
	k: bigint
	bump: number
}

export type VaultArgs = {
	owner: ReadonlyUint8Array
	vaultId: ReadonlyUint8Array
	tokenMintA: ReadonlyUint8Array
	tokenMintB: ReadonlyUint8Array
	tokenAccountA: ReadonlyUint8Array
	tokenAccountB: ReadonlyUint8Array
	tokenProgramA: ReadonlyUint8Array
	tokenProgramB: ReadonlyUint8Array
	reserveA: number | bigint
	reserveB: number | bigint
	k: number | bigint
	bump: number
}

/** Gets the encoder for {@link VaultArgs} account data. */
export function getVaultEncoder(): FixedSizeEncoder<VaultArgs> {
	return getStructEncoder([
		["owner", fixEncoderSize(getBytesEncoder(), 32)],
		["vaultId", fixEncoderSize(getBytesEncoder(), 32)],
		["tokenMintA", fixEncoderSize(getBytesEncoder(), 32)],
		["tokenMintB", fixEncoderSize(getBytesEncoder(), 32)],
		["tokenAccountA", fixEncoderSize(getBytesEncoder(), 32)],
		["tokenAccountB", fixEncoderSize(getBytesEncoder(), 32)],
		["tokenProgramA", fixEncoderSize(getBytesEncoder(), 32)],
		["tokenProgramB", fixEncoderSize(getBytesEncoder(), 32)],
		["reserveA", getU64Encoder()],
		["reserveB", getU64Encoder()],
		["k", getU128Encoder()],
		["bump", getU8Encoder()]
	])
}

/** Gets the decoder for {@link Vault} account data. */
export function getVaultDecoder(): FixedSizeDecoder<Vault> {
	return getStructDecoder([
		["owner", fixDecoderSize(getBytesDecoder(), 32)],
		["vaultId", fixDecoderSize(getBytesDecoder(), 32)],
		["tokenMintA", fixDecoderSize(getBytesDecoder(), 32)],
		["tokenMintB", fixDecoderSize(getBytesDecoder(), 32)],
		["tokenAccountA", fixDecoderSize(getBytesDecoder(), 32)],
		["tokenAccountB", fixDecoderSize(getBytesDecoder(), 32)],
		["tokenProgramA", fixDecoderSize(getBytesDecoder(), 32)],
		["tokenProgramB", fixDecoderSize(getBytesDecoder(), 32)],
		["reserveA", getU64Decoder()],
		["reserveB", getU64Decoder()],
		["k", getU128Decoder()],
		["bump", getU8Decoder()]
	])
}

/** Gets the codec for {@link Vault} account data. */
export function getVaultCodec(): FixedSizeCodec<VaultArgs, Vault> {
	return combineCodec(getVaultEncoder(), getVaultDecoder())
}

export function decodeVault<TAddress extends string = string>(
	encodedAccount: EncodedAccount<TAddress>
): Account<Vault, TAddress>
export function decodeVault<TAddress extends string = string>(
	encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<Vault, TAddress>
export function decodeVault<TAddress extends string = string>(
	encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
): Account<Vault, TAddress> | MaybeAccount<Vault, TAddress> {
	return decodeAccount(encodedAccount as MaybeEncodedAccount<TAddress>, getVaultDecoder())
}

export async function fetchVault<TAddress extends string = string>(
	rpc: Parameters<typeof fetchEncodedAccount>[0],
	address: Address<TAddress>,
	config?: FetchAccountConfig
): Promise<Account<Vault, TAddress>> {
	const maybeAccount = await fetchMaybeVault(rpc, address, config)
	assertAccountExists(maybeAccount)
	return maybeAccount
}

export async function fetchMaybeVault<TAddress extends string = string>(
	rpc: Parameters<typeof fetchEncodedAccount>[0],
	address: Address<TAddress>,
	config?: FetchAccountConfig
): Promise<MaybeAccount<Vault, TAddress>> {
	const maybeAccount = await fetchEncodedAccount(rpc, address, config)
	return decodeVault(maybeAccount)
}

export async function fetchAllVault(
	rpc: Parameters<typeof fetchEncodedAccounts>[0],
	addresses: Array<Address>,
	config?: FetchAccountsConfig
): Promise<Account<Vault>[]> {
	const maybeAccounts = await fetchAllMaybeVault(rpc, addresses, config)
	assertAccountsExist(maybeAccounts)
	return maybeAccounts
}

export async function fetchAllMaybeVault(
	rpc: Parameters<typeof fetchEncodedAccounts>[0],
	addresses: Array<Address>,
	config?: FetchAccountsConfig
): Promise<MaybeAccount<Vault>[]> {
	const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config)
	return maybeAccounts.map(maybeAccount => decodeVault(maybeAccount))
}

export function getVaultSize(): number {
	return 289
}
