/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { type Address, containsBytes, getU8Encoder, type ReadonlyUint8Array } from "@solana/kit"
import type {
	ParsedIncreaseCounterAuthorityInstruction,
	ParsedIncreaseCounterInstruction,
	ParsedInitCounterAuhthorityInstruction,
	ParsedInitCounterInstruction
} from "../instructions"

export const COUNTER_PROGRAM_ADDRESS =
	"8F1XtWR4wTs37nnutBvd2MWpCTfb7XAciFYkw5XHaENj" as Address<"8F1XtWR4wTs37nnutBvd2MWpCTfb7XAciFYkw5XHaENj">

export enum CounterAccount {
	Counter,
	CounterAuthority
}

export enum CounterInstruction {
	InitCounter,
	IncreaseCounter,
	InitCounterAuhthority,
	IncreaseCounterAuthority
}

export function identifyCounterInstruction(
	instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): CounterInstruction {
	const data = "data" in instruction ? instruction.data : instruction
	if (containsBytes(data, getU8Encoder().encode(0), 0)) {
		return CounterInstruction.InitCounter
	}
	if (containsBytes(data, getU8Encoder().encode(1), 0)) {
		return CounterInstruction.IncreaseCounter
	}
	if (containsBytes(data, getU8Encoder().encode(2), 0)) {
		return CounterInstruction.InitCounterAuhthority
	}
	if (containsBytes(data, getU8Encoder().encode(3), 0)) {
		return CounterInstruction.IncreaseCounterAuthority
	}
	throw new Error("The provided instruction could not be identified as a counter instruction.")
}

export type ParsedCounterInstruction<
	TProgram extends string = "8F1XtWR4wTs37nnutBvd2MWpCTfb7XAciFYkw5XHaENj"
> =
	| ({
			instructionType: CounterInstruction.InitCounter
	  } & ParsedInitCounterInstruction<TProgram>)
	| ({
			instructionType: CounterInstruction.IncreaseCounter
	  } & ParsedIncreaseCounterInstruction<TProgram>)
	| ({
			instructionType: CounterInstruction.InitCounterAuhthority
	  } & ParsedInitCounterAuhthorityInstruction<TProgram>)
	| ({
			instructionType: CounterInstruction.IncreaseCounterAuthority
	  } & ParsedIncreaseCounterAuthorityInstruction<TProgram>)
