/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type Address,
	isProgramError,
	type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
	type SolanaError
} from "@solana/kit"
import { FULL_SHANK_PROGRAM_ADDRESS } from "../programs"

/** NotAdmin: Caller is not the board admin */
export const FULL_SHANK_ERROR__NOT_ADMIN = 0x0 // 0
/** BoardAlreadyInitialized: Board has already been initialized */
export const FULL_SHANK_ERROR__BOARD_ALREADY_INITIALIZED = 0x1 // 1
/** BoardNotInitialized: Board has not been initialized */
export const FULL_SHANK_ERROR__BOARD_NOT_INITIALIZED = 0x2 // 2
/** ProfileAlreadyExists: Profile already exists for this authority */
export const FULL_SHANK_ERROR__PROFILE_ALREADY_EXISTS = 0x3 // 3
/** ProfileNotFound: Profile not found for this authority */
export const FULL_SHANK_ERROR__PROFILE_NOT_FOUND = 0x4 // 4
/** NotAuthor: Caller is not the post author */
export const FULL_SHANK_ERROR__NOT_AUTHOR = 0x5 // 5
/** PostAlreadyDeleted: Post has already been deleted */
export const FULL_SHANK_ERROR__POST_ALREADY_DELETED = 0x6 // 6
/** UserSuspended: User account is suspended */
export const FULL_SHANK_ERROR__USER_SUSPENDED = 0x7 // 7
/** NumericalOverflow: Numerical overflow */
export const FULL_SHANK_ERROR__NUMERICAL_OVERFLOW = 0x8 // 8

export type FullShankError =
	| typeof FULL_SHANK_ERROR__BOARD_ALREADY_INITIALIZED
	| typeof FULL_SHANK_ERROR__BOARD_NOT_INITIALIZED
	| typeof FULL_SHANK_ERROR__NOT_ADMIN
	| typeof FULL_SHANK_ERROR__NOT_AUTHOR
	| typeof FULL_SHANK_ERROR__NUMERICAL_OVERFLOW
	| typeof FULL_SHANK_ERROR__POST_ALREADY_DELETED
	| typeof FULL_SHANK_ERROR__PROFILE_ALREADY_EXISTS
	| typeof FULL_SHANK_ERROR__PROFILE_NOT_FOUND
	| typeof FULL_SHANK_ERROR__USER_SUSPENDED

let fullShankErrorMessages: Record<FullShankError, string> | undefined
if (process.env.NODE_ENV !== "production") {
	fullShankErrorMessages = {
		[FULL_SHANK_ERROR__BOARD_ALREADY_INITIALIZED]: `Board has already been initialized`,
		[FULL_SHANK_ERROR__BOARD_NOT_INITIALIZED]: `Board has not been initialized`,
		[FULL_SHANK_ERROR__NOT_ADMIN]: `Caller is not the board admin`,
		[FULL_SHANK_ERROR__NOT_AUTHOR]: `Caller is not the post author`,
		[FULL_SHANK_ERROR__NUMERICAL_OVERFLOW]: `Numerical overflow`,
		[FULL_SHANK_ERROR__POST_ALREADY_DELETED]: `Post has already been deleted`,
		[FULL_SHANK_ERROR__PROFILE_ALREADY_EXISTS]: `Profile already exists for this authority`,
		[FULL_SHANK_ERROR__PROFILE_NOT_FOUND]: `Profile not found for this authority`,
		[FULL_SHANK_ERROR__USER_SUSPENDED]: `User account is suspended`
	}
}

export function getFullShankErrorMessage(code: FullShankError): string {
	if (process.env.NODE_ENV !== "production") {
		return (fullShankErrorMessages as Record<FullShankError, string>)[code]
	}

	return "Error message not available in production bundles."
}

export function isFullShankError<TProgramErrorCode extends FullShankError>(
	error: unknown,
	transactionMessage: {
		instructions: Record<number, { programAddress: Address }>
	},
	code?: TProgramErrorCode
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
	Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
	return isProgramError<TProgramErrorCode>(
		error,
		transactionMessage,
		FULL_SHANK_PROGRAM_ADDRESS,
		code
	)
}
