/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type AccountMeta,
	type AccountSignerMeta,
	type Address,
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	getStructDecoder,
	getStructEncoder,
	getU8Decoder,
	getU8Encoder,
	type Instruction,
	type InstructionWithAccounts,
	type InstructionWithData,
	type ReadonlyAccount,
	type ReadonlySignerAccount,
	type ReadonlyUint8Array,
	type TransactionSigner,
	transformEncoder,
	type WritableAccount
} from "@solana/kit"
import { CLOSE_ACCOUNT_PROGRAM_ADDRESS } from "../programs"
import { getAccountMetaFactory, type ResolvedAccount } from "../shared"

export const CLOSE_MEME_DISCRIMINATOR = 1

export function getCloseMemeDiscriminatorBytes() {
	return getU8Encoder().encode(CLOSE_MEME_DISCRIMINATOR)
}

export type CloseMemeInstruction<
	TProgram extends string = typeof CLOSE_ACCOUNT_PROGRAM_ADDRESS,
	TAccountPayer extends string | AccountMeta<string> = string,
	TAccountMeme extends string | AccountMeta<string> = string,
	TAccountSystemProgram extends string | AccountMeta<string> = "11111111111111111111111111111111",
	TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
	InstructionWithData<ReadonlyUint8Array> &
	InstructionWithAccounts<
		[
			TAccountPayer extends string
				? ReadonlySignerAccount<TAccountPayer> & AccountSignerMeta<TAccountPayer>
				: TAccountPayer,
			TAccountMeme extends string ? WritableAccount<TAccountMeme> : TAccountMeme,
			TAccountSystemProgram extends string
				? ReadonlyAccount<TAccountSystemProgram>
				: TAccountSystemProgram,
			...TRemainingAccounts
		]
	>

export type CloseMemeInstructionData = { discriminator: number }

export type CloseMemeInstructionDataArgs = {}

export function getCloseMemeInstructionDataEncoder(): FixedSizeEncoder<CloseMemeInstructionDataArgs> {
	return transformEncoder(getStructEncoder([["discriminator", getU8Encoder()]]), value => ({
		...value,
		discriminator: CLOSE_MEME_DISCRIMINATOR
	}))
}

export function getCloseMemeInstructionDataDecoder(): FixedSizeDecoder<CloseMemeInstructionData> {
	return getStructDecoder([["discriminator", getU8Decoder()]])
}

export function getCloseMemeInstructionDataCodec(): FixedSizeCodec<
	CloseMemeInstructionDataArgs,
	CloseMemeInstructionData
> {
	return combineCodec(getCloseMemeInstructionDataEncoder(), getCloseMemeInstructionDataDecoder())
}

export type CloseMemeInput<
	TAccountPayer extends string = string,
	TAccountMeme extends string = string,
	TAccountSystemProgram extends string = string
> = {
	payer: TransactionSigner<TAccountPayer>
	meme: Address<TAccountMeme>
	systemProgram?: Address<TAccountSystemProgram>
}

export function getCloseMemeInstruction<
	TAccountPayer extends string,
	TAccountMeme extends string,
	TAccountSystemProgram extends string,
	TProgramAddress extends Address = typeof CLOSE_ACCOUNT_PROGRAM_ADDRESS
>(
	input: CloseMemeInput<TAccountPayer, TAccountMeme, TAccountSystemProgram>,
	config?: { programAddress?: TProgramAddress }
): CloseMemeInstruction<TProgramAddress, TAccountPayer, TAccountMeme, TAccountSystemProgram> {
	// Program address.
	const programAddress = config?.programAddress ?? CLOSE_ACCOUNT_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		payer: { value: input.payer ?? null, isWritable: false },
		meme: { value: input.meme ?? null, isWritable: true },
		systemProgram: { value: input.systemProgram ?? null, isWritable: false }
	}
	const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedAccount>

	// Resolve default values.
	if (!accounts.systemProgram.value) {
		accounts.systemProgram.value =
			"11111111111111111111111111111111" as Address<"11111111111111111111111111111111">
	}

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta(accounts.payer),
			getAccountMeta(accounts.meme),
			getAccountMeta(accounts.systemProgram)
		],
		data: getCloseMemeInstructionDataEncoder().encode({}),
		programAddress
	} as CloseMemeInstruction<TProgramAddress, TAccountPayer, TAccountMeme, TAccountSystemProgram>)
}

export type ParsedCloseMemeInstruction<
	TProgram extends string = typeof CLOSE_ACCOUNT_PROGRAM_ADDRESS,
	TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
	programAddress: Address<TProgram>
	accounts: {
		payer: TAccountMetas[0]
		meme: TAccountMetas[1]
		systemProgram: TAccountMetas[2]
	}
	data: CloseMemeInstructionData
}

export function parseCloseMemeInstruction<
	TProgram extends string,
	TAccountMetas extends readonly AccountMeta[]
>(
	instruction: Instruction<TProgram> &
		InstructionWithAccounts<TAccountMetas> &
		InstructionWithData<ReadonlyUint8Array>
): ParsedCloseMemeInstruction<TProgram, TAccountMetas> {
	if (instruction.accounts.length < 3) {
		// TODO: Coded error.
		throw new Error("Not enough accounts")
	}
	let accountIndex = 0
	const getNextAccount = () => {
		const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!
		accountIndex += 1
		return accountMeta
	}
	return {
		programAddress: instruction.programAddress,
		accounts: {
			payer: getNextAccount(),
			meme: getNextAccount(),
			systemProgram: getNextAccount()
		},
		data: getCloseMemeInstructionDataDecoder().decode(instruction.data)
	}
}
