/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type AccountMeta,
	type AccountSignerMeta,
	type Address,
	type Codec,
	combineCodec,
	type Decoder,
	type Encoder,
	getStructDecoder,
	getStructEncoder,
	getU8Decoder,
	getU8Encoder,
	type Instruction,
	type InstructionWithAccounts,
	type InstructionWithData,
	type ReadonlyAccount,
	type ReadonlySignerAccount,
	type ReadonlyUint8Array,
	type TransactionSigner,
	transformEncoder,
	type WritableAccount
} from "@solana/kit"
import { COUNTER_PROGRAM_ADDRESS } from "../programs"
import { getAccountMetaFactory, type ResolvedAccount } from "../shared"
import {
	getInitCounterDecoder,
	getInitCounterEncoder,
	type InitCounter,
	type InitCounterArgs
} from "../types"

export const INIT_COUNTER_DISCRIMINATOR = 0

export function getInitCounterDiscriminatorBytes() {
	return getU8Encoder().encode(INIT_COUNTER_DISCRIMINATOR)
}

export type InitCounterInstruction<
	TProgram extends string = typeof COUNTER_PROGRAM_ADDRESS,
	TAccountPayer extends string | AccountMeta<string> = string,
	TAccountCounter extends string | AccountMeta<string> = string,
	TAccountSystemProgram extends string | AccountMeta<string> = "11111111111111111111111111111111",
	TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
	InstructionWithData<ReadonlyUint8Array> &
	InstructionWithAccounts<
		[
			TAccountPayer extends string
				? ReadonlySignerAccount<TAccountPayer> & AccountSignerMeta<TAccountPayer>
				: TAccountPayer,
			TAccountCounter extends string ? WritableAccount<TAccountCounter> : TAccountCounter,
			TAccountSystemProgram extends string
				? ReadonlyAccount<TAccountSystemProgram>
				: TAccountSystemProgram,
			...TRemainingAccounts
		]
	>

export type InitCounterInstructionData = {
	discriminator: number
	initCounter: InitCounter
}

export type InitCounterInstructionDataArgs = { initCounter: InitCounterArgs }

export function getInitCounterInstructionDataEncoder(): Encoder<InitCounterInstructionDataArgs> {
	return transformEncoder(
		getStructEncoder([
			["discriminator", getU8Encoder()],
			["initCounter", getInitCounterEncoder()]
		]),
		value => ({ ...value, discriminator: INIT_COUNTER_DISCRIMINATOR })
	)
}

export function getInitCounterInstructionDataDecoder(): Decoder<InitCounterInstructionData> {
	return getStructDecoder([
		["discriminator", getU8Decoder()],
		["initCounter", getInitCounterDecoder()]
	])
}

export function getInitCounterInstructionDataCodec(): Codec<
	InitCounterInstructionDataArgs,
	InitCounterInstructionData
> {
	return combineCodec(
		getInitCounterInstructionDataEncoder(),
		getInitCounterInstructionDataDecoder()
	)
}

export type InitCounterInput<
	TAccountPayer extends string = string,
	TAccountCounter extends string = string,
	TAccountSystemProgram extends string = string
> = {
	payer: TransactionSigner<TAccountPayer>
	counter: Address<TAccountCounter>
	systemProgram?: Address<TAccountSystemProgram>
	initCounter: InitCounterInstructionDataArgs["initCounter"]
}

export function getInitCounterInstruction<
	TAccountPayer extends string,
	TAccountCounter extends string,
	TAccountSystemProgram extends string,
	TProgramAddress extends Address = typeof COUNTER_PROGRAM_ADDRESS
>(
	input: InitCounterInput<TAccountPayer, TAccountCounter, TAccountSystemProgram>,
	config?: { programAddress?: TProgramAddress }
): InitCounterInstruction<TProgramAddress, TAccountPayer, TAccountCounter, TAccountSystemProgram> {
	// Program address.
	const programAddress = config?.programAddress ?? COUNTER_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		payer: { value: input.payer ?? null, isWritable: false },
		counter: { value: input.counter ?? null, isWritable: true },
		systemProgram: { value: input.systemProgram ?? null, isWritable: false }
	}
	const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedAccount>

	// Original args.
	const args = { ...input }

	// Resolve default values.
	if (!accounts.systemProgram.value) {
		accounts.systemProgram.value =
			"11111111111111111111111111111111" as Address<"11111111111111111111111111111111">
	}

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta(accounts.payer),
			getAccountMeta(accounts.counter),
			getAccountMeta(accounts.systemProgram)
		],
		data: getInitCounterInstructionDataEncoder().encode(args as InitCounterInstructionDataArgs),
		programAddress
	} as InitCounterInstruction<
		TProgramAddress,
		TAccountPayer,
		TAccountCounter,
		TAccountSystemProgram
	>)
}

export type ParsedInitCounterInstruction<
	TProgram extends string = typeof COUNTER_PROGRAM_ADDRESS,
	TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
	programAddress: Address<TProgram>
	accounts: {
		payer: TAccountMetas[0]
		counter: TAccountMetas[1]
		systemProgram: TAccountMetas[2]
	}
	data: InitCounterInstructionData
}

export function parseInitCounterInstruction<
	TProgram extends string,
	TAccountMetas extends readonly AccountMeta[]
>(
	instruction: Instruction<TProgram> &
		InstructionWithAccounts<TAccountMetas> &
		InstructionWithData<ReadonlyUint8Array>
): ParsedInitCounterInstruction<TProgram, TAccountMetas> {
	if (instruction.accounts.length < 3) {
		// TODO: Coded error.
		throw new Error("Not enough accounts")
	}
	let accountIndex = 0
	const getNextAccount = () => {
		const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!
		accountIndex += 1
		return accountMeta
	}
	return {
		programAddress: instruction.programAddress,
		accounts: {
			payer: getNextAccount(),
			counter: getNextAccount(),
			systemProgram: getNextAccount()
		},
		data: getInitCounterInstructionDataDecoder().decode(instruction.data)
	}
}
