/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type AccountMeta,
	type AccountSignerMeta,
	type Address,
	type Codec,
	combineCodec,
	type Decoder,
	type Encoder,
	getStructDecoder,
	getStructEncoder,
	getU8Decoder,
	getU8Encoder,
	type Instruction,
	type InstructionWithAccounts,
	type InstructionWithData,
	type ReadonlyAccount,
	type ReadonlySignerAccount,
	type ReadonlyUint8Array,
	type TransactionSigner,
	transformEncoder,
	type WritableAccount
} from "@solana/kit"
import { COUNTER_PROGRAM_ADDRESS } from "../programs"
import { getAccountMetaFactory, type ResolvedAccount } from "../shared"
import {
	getInitCounterAuthorityDecoder,
	getInitCounterAuthorityEncoder,
	type InitCounterAuthority,
	type InitCounterAuthorityArgs
} from "../types"

export const INIT_COUNTER_AUHTHORITY_DISCRIMINATOR = 2

export function getInitCounterAuhthorityDiscriminatorBytes() {
	return getU8Encoder().encode(INIT_COUNTER_AUHTHORITY_DISCRIMINATOR)
}

export type InitCounterAuhthorityInstruction<
	TProgram extends string = typeof COUNTER_PROGRAM_ADDRESS,
	TAccountPayer extends string | AccountMeta<string> = string,
	TAccountCounterAuthority extends string | AccountMeta<string> = string,
	TAccountSystemProgram extends string | AccountMeta<string> = "11111111111111111111111111111111",
	TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
	InstructionWithData<ReadonlyUint8Array> &
	InstructionWithAccounts<
		[
			TAccountPayer extends string
				? ReadonlySignerAccount<TAccountPayer> & AccountSignerMeta<TAccountPayer>
				: TAccountPayer,
			TAccountCounterAuthority extends string
				? WritableAccount<TAccountCounterAuthority>
				: TAccountCounterAuthority,
			TAccountSystemProgram extends string
				? ReadonlyAccount<TAccountSystemProgram>
				: TAccountSystemProgram,
			...TRemainingAccounts
		]
	>

export type InitCounterAuhthorityInstructionData = {
	discriminator: number
	initCounterAuthority: InitCounterAuthority
}

export type InitCounterAuhthorityInstructionDataArgs = {
	initCounterAuthority: InitCounterAuthorityArgs
}

export function getInitCounterAuhthorityInstructionDataEncoder(): Encoder<InitCounterAuhthorityInstructionDataArgs> {
	return transformEncoder(
		getStructEncoder([
			["discriminator", getU8Encoder()],
			["initCounterAuthority", getInitCounterAuthorityEncoder()]
		]),
		value => ({
			...value,
			discriminator: INIT_COUNTER_AUHTHORITY_DISCRIMINATOR
		})
	)
}

export function getInitCounterAuhthorityInstructionDataDecoder(): Decoder<InitCounterAuhthorityInstructionData> {
	return getStructDecoder([
		["discriminator", getU8Decoder()],
		["initCounterAuthority", getInitCounterAuthorityDecoder()]
	])
}

export function getInitCounterAuhthorityInstructionDataCodec(): Codec<
	InitCounterAuhthorityInstructionDataArgs,
	InitCounterAuhthorityInstructionData
> {
	return combineCodec(
		getInitCounterAuhthorityInstructionDataEncoder(),
		getInitCounterAuhthorityInstructionDataDecoder()
	)
}

export type InitCounterAuhthorityInput<
	TAccountPayer extends string = string,
	TAccountCounterAuthority extends string = string,
	TAccountSystemProgram extends string = string
> = {
	payer: TransactionSigner<TAccountPayer>
	counterAuthority: Address<TAccountCounterAuthority>
	systemProgram?: Address<TAccountSystemProgram>
	initCounterAuthority: InitCounterAuhthorityInstructionDataArgs["initCounterAuthority"]
}

export function getInitCounterAuhthorityInstruction<
	TAccountPayer extends string,
	TAccountCounterAuthority extends string,
	TAccountSystemProgram extends string,
	TProgramAddress extends Address = typeof COUNTER_PROGRAM_ADDRESS
>(
	input: InitCounterAuhthorityInput<TAccountPayer, TAccountCounterAuthority, TAccountSystemProgram>,
	config?: { programAddress?: TProgramAddress }
): InitCounterAuhthorityInstruction<
	TProgramAddress,
	TAccountPayer,
	TAccountCounterAuthority,
	TAccountSystemProgram
> {
	// Program address.
	const programAddress = config?.programAddress ?? COUNTER_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		payer: { value: input.payer ?? null, isWritable: false },
		counterAuthority: {
			value: input.counterAuthority ?? null,
			isWritable: true
		},
		systemProgram: { value: input.systemProgram ?? null, isWritable: false }
	}
	const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedAccount>

	// Original args.
	const args = { ...input }

	// Resolve default values.
	if (!accounts.systemProgram.value) {
		accounts.systemProgram.value =
			"11111111111111111111111111111111" as Address<"11111111111111111111111111111111">
	}

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta(accounts.payer),
			getAccountMeta(accounts.counterAuthority),
			getAccountMeta(accounts.systemProgram)
		],
		data: getInitCounterAuhthorityInstructionDataEncoder().encode(
			args as InitCounterAuhthorityInstructionDataArgs
		),
		programAddress
	} as InitCounterAuhthorityInstruction<
		TProgramAddress,
		TAccountPayer,
		TAccountCounterAuthority,
		TAccountSystemProgram
	>)
}

export type ParsedInitCounterAuhthorityInstruction<
	TProgram extends string = typeof COUNTER_PROGRAM_ADDRESS,
	TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
	programAddress: Address<TProgram>
	accounts: {
		payer: TAccountMetas[0]
		counterAuthority: TAccountMetas[1]
		systemProgram: TAccountMetas[2]
	}
	data: InitCounterAuhthorityInstructionData
}

export function parseInitCounterAuhthorityInstruction<
	TProgram extends string,
	TAccountMetas extends readonly AccountMeta[]
>(
	instruction: Instruction<TProgram> &
		InstructionWithAccounts<TAccountMetas> &
		InstructionWithData<ReadonlyUint8Array>
): ParsedInitCounterAuhthorityInstruction<TProgram, TAccountMetas> {
	if (instruction.accounts.length < 3) {
		// TODO: Coded error.
		throw new Error("Not enough accounts")
	}
	let accountIndex = 0
	const getNextAccount = () => {
		const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!
		accountIndex += 1
		return accountMeta
	}
	return {
		programAddress: instruction.programAddress,
		accounts: {
			payer: getNextAccount(),
			counterAuthority: getNextAccount(),
			systemProgram: getNextAccount()
		},
		data: getInitCounterAuhthorityInstructionDataDecoder().decode(instruction.data)
	}
}
