/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type Address,
	assertIsInstructionWithAccounts,
	type ClientWithPayer,
	type ClientWithRpc,
	type ClientWithTransactionPlanning,
	type ClientWithTransactionSending,
	containsBytes,
	type GetAccountInfoApi,
	type GetMultipleAccountsApi,
	getU8Encoder,
	type Instruction,
	type InstructionWithData,
	type ReadonlyUint8Array,
	SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_INSTRUCTION,
	SOLANA_ERROR__PROGRAM_CLIENTS__UNRECOGNIZED_INSTRUCTION_TYPE,
	SolanaError
} from "@solana/kit"
import {
	addSelfFetchFunctions,
	addSelfPlanAndSendFunctions,
	type SelfFetchFunctions,
	type SelfPlanAndSendFunctions
} from "@solana/program-client-core"
import {
	type BoardConfig,
	type BoardConfigArgs,
	getBoardConfigCodec,
	getPostCodec,
	getUserProfileCodec,
	type Post,
	type PostArgs,
	type UserProfile,
	type UserProfileArgs
} from "../accounts"
import {
	type CreateProfileInput,
	type DeletePostInput,
	getCreateProfileInstruction,
	getDeletePostInstruction,
	getInitBoardInstruction,
	getPostMessageInstruction,
	getSuspendProfileInstruction,
	getUpdateUsernameInstruction,
	type InitBoardInput,
	type ParsedCreateProfileInstruction,
	type ParsedDeletePostInstruction,
	type ParsedInitBoardInstruction,
	type ParsedPostMessageInstruction,
	type ParsedSuspendProfileInstruction,
	type ParsedUpdateUsernameInstruction,
	type PostMessageInput,
	parseCreateProfileInstruction,
	parseDeletePostInstruction,
	parseInitBoardInstruction,
	parsePostMessageInstruction,
	parseSuspendProfileInstruction,
	parseUpdateUsernameInstruction,
	type SuspendProfileInput,
	type UpdateUsernameInput
} from "../instructions"

export const FULL_SHANK_PROGRAM_ADDRESS =
	"FuLLShankNoteBoardProg111111111111111111111" as Address<"FuLLShankNoteBoardProg111111111111111111111">

export enum FullShankAccount {
	BoardConfig,
	UserProfile,
	Post
}

export enum FullShankInstruction {
	InitBoard,
	CreateProfile,
	PostMessage,
	UpdateUsername,
	DeletePost,
	SuspendProfile
}

export function identifyFullShankInstruction(
	instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): FullShankInstruction {
	const data = "data" in instruction ? instruction.data : instruction
	if (containsBytes(data, getU8Encoder().encode(0), 0)) {
		return FullShankInstruction.InitBoard
	}
	if (containsBytes(data, getU8Encoder().encode(1), 0)) {
		return FullShankInstruction.CreateProfile
	}
	if (containsBytes(data, getU8Encoder().encode(2), 0)) {
		return FullShankInstruction.PostMessage
	}
	if (containsBytes(data, getU8Encoder().encode(3), 0)) {
		return FullShankInstruction.UpdateUsername
	}
	if (containsBytes(data, getU8Encoder().encode(4), 0)) {
		return FullShankInstruction.DeletePost
	}
	if (containsBytes(data, getU8Encoder().encode(5), 0)) {
		return FullShankInstruction.SuspendProfile
	}
	throw new SolanaError(SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_INSTRUCTION, {
		instructionData: data,
		programName: "fullShank"
	})
}

export type ParsedFullShankInstruction<
	TProgram extends string = "FuLLShankNoteBoardProg111111111111111111111"
> =
	| ({
			instructionType: FullShankInstruction.InitBoard
	  } & ParsedInitBoardInstruction<TProgram>)
	| ({
			instructionType: FullShankInstruction.CreateProfile
	  } & ParsedCreateProfileInstruction<TProgram>)
	| ({
			instructionType: FullShankInstruction.PostMessage
	  } & ParsedPostMessageInstruction<TProgram>)
	| ({
			instructionType: FullShankInstruction.UpdateUsername
	  } & ParsedUpdateUsernameInstruction<TProgram>)
	| ({
			instructionType: FullShankInstruction.DeletePost
	  } & ParsedDeletePostInstruction<TProgram>)
	| ({
			instructionType: FullShankInstruction.SuspendProfile
	  } & ParsedSuspendProfileInstruction<TProgram>)

export function parseFullShankInstruction<TProgram extends string>(
	instruction: Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array>
): ParsedFullShankInstruction<TProgram> {
	const instructionType = identifyFullShankInstruction(instruction)
	switch (instructionType) {
		case FullShankInstruction.InitBoard: {
			assertIsInstructionWithAccounts(instruction)
			return {
				instructionType: FullShankInstruction.InitBoard,
				...parseInitBoardInstruction(instruction)
			}
		}
		case FullShankInstruction.CreateProfile: {
			assertIsInstructionWithAccounts(instruction)
			return {
				instructionType: FullShankInstruction.CreateProfile,
				...parseCreateProfileInstruction(instruction)
			}
		}
		case FullShankInstruction.PostMessage: {
			assertIsInstructionWithAccounts(instruction)
			return {
				instructionType: FullShankInstruction.PostMessage,
				...parsePostMessageInstruction(instruction)
			}
		}
		case FullShankInstruction.UpdateUsername: {
			assertIsInstructionWithAccounts(instruction)
			return {
				instructionType: FullShankInstruction.UpdateUsername,
				...parseUpdateUsernameInstruction(instruction)
			}
		}
		case FullShankInstruction.DeletePost: {
			assertIsInstructionWithAccounts(instruction)
			return {
				instructionType: FullShankInstruction.DeletePost,
				...parseDeletePostInstruction(instruction)
			}
		}
		case FullShankInstruction.SuspendProfile: {
			assertIsInstructionWithAccounts(instruction)
			return {
				instructionType: FullShankInstruction.SuspendProfile,
				...parseSuspendProfileInstruction(instruction)
			}
		}
		default:
			throw new SolanaError(SOLANA_ERROR__PROGRAM_CLIENTS__UNRECOGNIZED_INSTRUCTION_TYPE, {
				instructionType: instructionType as string,
				programName: "fullShank"
			})
	}
}

export type FullShankPlugin = {
	accounts: FullShankPluginAccounts
	instructions: FullShankPluginInstructions
}

export type FullShankPluginAccounts = {
	boardConfig: ReturnType<typeof getBoardConfigCodec> &
		SelfFetchFunctions<BoardConfigArgs, BoardConfig>
	userProfile: ReturnType<typeof getUserProfileCodec> &
		SelfFetchFunctions<UserProfileArgs, UserProfile>
	post: ReturnType<typeof getPostCodec> & SelfFetchFunctions<PostArgs, Post>
}

export type FullShankPluginInstructions = {
	initBoard: (
		input: InitBoardInput
	) => ReturnType<typeof getInitBoardInstruction> & SelfPlanAndSendFunctions
	createProfile: (
		input: MakeOptional<CreateProfileInput, "payer">
	) => ReturnType<typeof getCreateProfileInstruction> & SelfPlanAndSendFunctions
	postMessage: (
		input: PostMessageInput
	) => ReturnType<typeof getPostMessageInstruction> & SelfPlanAndSendFunctions
	updateUsername: (
		input: UpdateUsernameInput
	) => ReturnType<typeof getUpdateUsernameInstruction> & SelfPlanAndSendFunctions
	deletePost: (
		input: DeletePostInput
	) => ReturnType<typeof getDeletePostInstruction> & SelfPlanAndSendFunctions
	suspendProfile: (
		input: SuspendProfileInput
	) => ReturnType<typeof getSuspendProfileInstruction> & SelfPlanAndSendFunctions
}

export type FullShankPluginRequirements = ClientWithRpc<
	GetAccountInfoApi & GetMultipleAccountsApi
> &
	ClientWithPayer &
	ClientWithTransactionPlanning &
	ClientWithTransactionSending

export function fullShankProgram() {
	return <T extends FullShankPluginRequirements>(client: T) => {
		return {
			...client,
			fullShank: <FullShankPlugin>{
				accounts: {
					boardConfig: addSelfFetchFunctions(client, getBoardConfigCodec()),
					userProfile: addSelfFetchFunctions(client, getUserProfileCodec()),
					post: addSelfFetchFunctions(client, getPostCodec())
				},
				instructions: {
					initBoard: input => addSelfPlanAndSendFunctions(client, getInitBoardInstruction(input)),
					createProfile: input =>
						addSelfPlanAndSendFunctions(
							client,
							getCreateProfileInstruction({
								...input,
								payer: input.payer ?? client.payer
							})
						),
					postMessage: input =>
						addSelfPlanAndSendFunctions(client, getPostMessageInstruction(input)),
					updateUsername: input =>
						addSelfPlanAndSendFunctions(client, getUpdateUsernameInstruction(input)),
					deletePost: input => addSelfPlanAndSendFunctions(client, getDeletePostInstruction(input)),
					suspendProfile: input =>
						addSelfPlanAndSendFunctions(client, getSuspendProfileInstruction(input))
				}
			}
		}
	}
}

type MakeOptional<T, K extends keyof T> = Omit<T, K> & Partial<Pick<T, K>>
