/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	fixDecoderSize,
	fixEncoderSize,
	getBytesDecoder,
	getBytesEncoder,
	getStructDecoder,
	getStructEncoder,
	getU64Decoder,
	getU64Encoder,
	type ReadonlyUint8Array
} from "@solana/kit"

export type SwapExactInExecuted = {
	vault: ReadonlyUint8Array
	amountIn: bigint
	amountOut: bigint
	reserveA: bigint
	reserveB: bigint
}

export type SwapExactInExecutedArgs = {
	vault: ReadonlyUint8Array
	amountIn: number | bigint
	amountOut: number | bigint
	reserveA: number | bigint
	reserveB: number | bigint
}

export function getSwapExactInExecutedEncoder(): FixedSizeEncoder<SwapExactInExecutedArgs> {
	return getStructEncoder([
		["vault", fixEncoderSize(getBytesEncoder(), 32)],
		["amountIn", getU64Encoder()],
		["amountOut", getU64Encoder()],
		["reserveA", getU64Encoder()],
		["reserveB", getU64Encoder()]
	])
}

export function getSwapExactInExecutedDecoder(): FixedSizeDecoder<SwapExactInExecuted> {
	return getStructDecoder([
		["vault", fixDecoderSize(getBytesDecoder(), 32)],
		["amountIn", getU64Decoder()],
		["amountOut", getU64Decoder()],
		["reserveA", getU64Decoder()],
		["reserveB", getU64Decoder()]
	])
}

export function getSwapExactInExecutedCodec(): FixedSizeCodec<
	SwapExactInExecutedArgs,
	SwapExactInExecuted
> {
	return combineCodec(getSwapExactInExecutedEncoder(), getSwapExactInExecutedDecoder())
}
