/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type Codec,
	combineCodec,
	type Decoder,
	type Encoder,
	type GetDiscriminatedUnionVariant,
	type GetDiscriminatedUnionVariantContent,
	getDiscriminatedUnionDecoder,
	getDiscriminatedUnionEncoder,
	getStructDecoder,
	getStructEncoder,
	getTupleDecoder,
	getTupleEncoder
} from "@solana/kit"
import {
	getSwapExactInExecutedDecoder,
	getSwapExactInExecutedEncoder,
	getSwapExactOutExecutedDecoder,
	getSwapExactOutExecutedEncoder,
	getVaultCreatedDecoder,
	getVaultCreatedEncoder,
	type SwapExactInExecuted,
	type SwapExactInExecutedArgs,
	type SwapExactOutExecuted,
	type SwapExactOutExecutedArgs,
	type VaultCreated,
	type VaultCreatedArgs
} from "."

export type VaultEvent =
	| { __kind: "VaultCreated"; fields: readonly [VaultCreated] }
	| { __kind: "SwapExactInExecuted"; fields: readonly [SwapExactInExecuted] }
	| { __kind: "SwapExactOutExecuted"; fields: readonly [SwapExactOutExecuted] }

export type VaultEventArgs =
	| { __kind: "VaultCreated"; fields: readonly [VaultCreatedArgs] }
	| {
			__kind: "SwapExactInExecuted"
			fields: readonly [SwapExactInExecutedArgs]
	  }
	| {
			__kind: "SwapExactOutExecuted"
			fields: readonly [SwapExactOutExecutedArgs]
	  }

export function getVaultEventEncoder(): Encoder<VaultEventArgs> {
	return getDiscriminatedUnionEncoder([
		["VaultCreated", getStructEncoder([["fields", getTupleEncoder([getVaultCreatedEncoder()])]])],
		[
			"SwapExactInExecuted",
			getStructEncoder([["fields", getTupleEncoder([getSwapExactInExecutedEncoder()])]])
		],
		[
			"SwapExactOutExecuted",
			getStructEncoder([["fields", getTupleEncoder([getSwapExactOutExecutedEncoder()])]])
		]
	])
}

export function getVaultEventDecoder(): Decoder<VaultEvent> {
	return getDiscriminatedUnionDecoder([
		["VaultCreated", getStructDecoder([["fields", getTupleDecoder([getVaultCreatedDecoder()])]])],
		[
			"SwapExactInExecuted",
			getStructDecoder([["fields", getTupleDecoder([getSwapExactInExecutedDecoder()])]])
		],
		[
			"SwapExactOutExecuted",
			getStructDecoder([["fields", getTupleDecoder([getSwapExactOutExecutedDecoder()])]])
		]
	])
}

export function getVaultEventCodec(): Codec<VaultEventArgs, VaultEvent> {
	return combineCodec(getVaultEventEncoder(), getVaultEventDecoder())
}

// Data Enum Helpers.
export function vaultEvent(
	kind: "VaultCreated",
	data: GetDiscriminatedUnionVariantContent<VaultEventArgs, "__kind", "VaultCreated">["fields"]
): GetDiscriminatedUnionVariant<VaultEventArgs, "__kind", "VaultCreated">
export function vaultEvent(
	kind: "SwapExactInExecuted",
	data: GetDiscriminatedUnionVariantContent<
		VaultEventArgs,
		"__kind",
		"SwapExactInExecuted"
	>["fields"]
): GetDiscriminatedUnionVariant<VaultEventArgs, "__kind", "SwapExactInExecuted">
export function vaultEvent(
	kind: "SwapExactOutExecuted",
	data: GetDiscriminatedUnionVariantContent<
		VaultEventArgs,
		"__kind",
		"SwapExactOutExecuted"
	>["fields"]
): GetDiscriminatedUnionVariant<VaultEventArgs, "__kind", "SwapExactOutExecuted">
export function vaultEvent<K extends VaultEventArgs["__kind"], Data>(kind: K, data?: Data) {
	return Array.isArray(data) ? { __kind: kind, fields: data } : { __kind: kind, ...(data ?? {}) }
}

export function isVaultEvent<K extends VaultEvent["__kind"]>(
	kind: K,
	value: VaultEvent
): value is VaultEvent & { __kind: K } {
	return value.__kind === kind
}
