/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	fixDecoderSize,
	fixEncoderSize,
	getBytesDecoder,
	getBytesEncoder,
	getStructDecoder,
	getStructEncoder,
	getU64Decoder,
	getU64Encoder,
	getU128Decoder,
	getU128Encoder,
	type ReadonlyUint8Array
} from "@solana/kit"

export type VaultCreated = {
	vault: ReadonlyUint8Array
	owner: ReadonlyUint8Array
	reserveA: bigint
	reserveB: bigint
	k: bigint
}

export type VaultCreatedArgs = {
	vault: ReadonlyUint8Array
	owner: ReadonlyUint8Array
	reserveA: number | bigint
	reserveB: number | bigint
	k: number | bigint
}

export function getVaultCreatedEncoder(): FixedSizeEncoder<VaultCreatedArgs> {
	return getStructEncoder([
		["vault", fixEncoderSize(getBytesEncoder(), 32)],
		["owner", fixEncoderSize(getBytesEncoder(), 32)],
		["reserveA", getU64Encoder()],
		["reserveB", getU64Encoder()],
		["k", getU128Encoder()]
	])
}

export function getVaultCreatedDecoder(): FixedSizeDecoder<VaultCreated> {
	return getStructDecoder([
		["vault", fixDecoderSize(getBytesDecoder(), 32)],
		["owner", fixDecoderSize(getBytesDecoder(), 32)],
		["reserveA", getU64Decoder()],
		["reserveB", getU64Decoder()],
		["k", getU128Decoder()]
	])
}

export function getVaultCreatedCodec(): FixedSizeCodec<VaultCreatedArgs, VaultCreated> {
	return combineCodec(getVaultCreatedEncoder(), getVaultCreatedDecoder())
}
