/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	getStructDecoder,
	getStructEncoder,
	getU64Decoder,
	getU64Encoder
} from "@solana/kit"

export type CounterAuthorityInitialized = { count: bigint }

export type CounterAuthorityInitializedArgs = { count: number | bigint }

export function getCounterAuthorityInitializedEncoder(): FixedSizeEncoder<CounterAuthorityInitializedArgs> {
	return getStructEncoder([["count", getU64Encoder()]])
}

export function getCounterAuthorityInitializedDecoder(): FixedSizeDecoder<CounterAuthorityInitialized> {
	return getStructDecoder([["count", getU64Decoder()]])
}

export function getCounterAuthorityInitializedCodec(): FixedSizeCodec<
	CounterAuthorityInitializedArgs,
	CounterAuthorityInitialized
> {
	return combineCodec(
		getCounterAuthorityInitializedEncoder(),
		getCounterAuthorityInitializedDecoder()
	)
}
