/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	getStructDecoder,
	getStructEncoder,
	getU64Decoder,
	getU64Encoder
} from "@solana/kit"

export type CounterIncreased = { newCount: bigint }

export type CounterIncreasedArgs = { newCount: number | bigint }

export function getCounterIncreasedEncoder(): FixedSizeEncoder<CounterIncreasedArgs> {
	return getStructEncoder([["newCount", getU64Encoder()]])
}

export function getCounterIncreasedDecoder(): FixedSizeDecoder<CounterIncreased> {
	return getStructDecoder([["newCount", getU64Decoder()]])
}

export function getCounterIncreasedCodec(): FixedSizeCodec<CounterIncreasedArgs, CounterIncreased> {
	return combineCodec(getCounterIncreasedEncoder(), getCounterIncreasedDecoder())
}
