/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	getStructDecoder,
	getStructEncoder,
	getU64Decoder,
	getU64Encoder
} from "@solana/kit"

export type CounterInitialized = { count: bigint }

export type CounterInitializedArgs = { count: number | bigint }

export function getCounterInitializedEncoder(): FixedSizeEncoder<CounterInitializedArgs> {
	return getStructEncoder([["count", getU64Encoder()]])
}

export function getCounterInitializedDecoder(): FixedSizeDecoder<CounterInitialized> {
	return getStructDecoder([["count", getU64Decoder()]])
}

export function getCounterInitializedCodec(): FixedSizeCodec<
	CounterInitializedArgs,
	CounterInitialized
> {
	return combineCodec(getCounterInitializedEncoder(), getCounterInitializedDecoder())
}
