/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	getStructDecoder,
	getStructEncoder,
	getU64Decoder,
	getU64Encoder
} from "@solana/kit"

export type CounterAuthorityIncreased = { newCount: bigint }

export type CounterAuthorityIncreasedArgs = { newCount: number | bigint }

export function getCounterAuthorityIncreasedEncoder(): FixedSizeEncoder<CounterAuthorityIncreasedArgs> {
	return getStructEncoder([["newCount", getU64Encoder()]])
}

export function getCounterAuthorityIncreasedDecoder(): FixedSizeDecoder<CounterAuthorityIncreased> {
	return getStructDecoder([["newCount", getU64Decoder()]])
}

export function getCounterAuthorityIncreasedCodec(): FixedSizeCodec<
	CounterAuthorityIncreasedArgs,
	CounterAuthorityIncreased
> {
	return combineCodec(getCounterAuthorityIncreasedEncoder(), getCounterAuthorityIncreasedDecoder())
}
