/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	type GetDiscriminatedUnionVariant,
	type GetDiscriminatedUnionVariantContent,
	getDiscriminatedUnionDecoder,
	getDiscriminatedUnionEncoder,
	getStructDecoder,
	getStructEncoder,
	getTupleDecoder,
	getTupleEncoder
} from "@solana/kit"
import {
	type CounterAuthorityIncreased,
	type CounterAuthorityIncreasedArgs,
	type CounterAuthorityInitialized,
	type CounterAuthorityInitializedArgs,
	type CounterIncreased,
	type CounterIncreasedArgs,
	type CounterInitialized,
	type CounterInitializedArgs,
	getCounterAuthorityIncreasedDecoder,
	getCounterAuthorityIncreasedEncoder,
	getCounterAuthorityInitializedDecoder,
	getCounterAuthorityInitializedEncoder,
	getCounterIncreasedDecoder,
	getCounterIncreasedEncoder,
	getCounterInitializedDecoder,
	getCounterInitializedEncoder
} from "."

export type CounterEvent =
	| { __kind: "CounterInitialized"; fields: readonly [CounterInitialized] }
	| { __kind: "CounterIncreased"; fields: readonly [CounterIncreased] }
	| {
			__kind: "CounterAuthorityInitialized"
			fields: readonly [CounterAuthorityInitialized]
	  }
	| {
			__kind: "CounterAuthorityIncreased"
			fields: readonly [CounterAuthorityIncreased]
	  }

export type CounterEventArgs =
	| { __kind: "CounterInitialized"; fields: readonly [CounterInitializedArgs] }
	| { __kind: "CounterIncreased"; fields: readonly [CounterIncreasedArgs] }
	| {
			__kind: "CounterAuthorityInitialized"
			fields: readonly [CounterAuthorityInitializedArgs]
	  }
	| {
			__kind: "CounterAuthorityIncreased"
			fields: readonly [CounterAuthorityIncreasedArgs]
	  }

export function getCounterEventEncoder(): FixedSizeEncoder<CounterEventArgs> {
	return getDiscriminatedUnionEncoder([
		[
			"CounterInitialized",
			getStructEncoder([["fields", getTupleEncoder([getCounterInitializedEncoder()])]])
		],
		[
			"CounterIncreased",
			getStructEncoder([["fields", getTupleEncoder([getCounterIncreasedEncoder()])]])
		],
		[
			"CounterAuthorityInitialized",
			getStructEncoder([["fields", getTupleEncoder([getCounterAuthorityInitializedEncoder()])]])
		],
		[
			"CounterAuthorityIncreased",
			getStructEncoder([["fields", getTupleEncoder([getCounterAuthorityIncreasedEncoder()])]])
		]
	]) as FixedSizeEncoder<CounterEventArgs>
}

export function getCounterEventDecoder(): FixedSizeDecoder<CounterEvent> {
	return getDiscriminatedUnionDecoder([
		[
			"CounterInitialized",
			getStructDecoder([["fields", getTupleDecoder([getCounterInitializedDecoder()])]])
		],
		[
			"CounterIncreased",
			getStructDecoder([["fields", getTupleDecoder([getCounterIncreasedDecoder()])]])
		],
		[
			"CounterAuthorityInitialized",
			getStructDecoder([["fields", getTupleDecoder([getCounterAuthorityInitializedDecoder()])]])
		],
		[
			"CounterAuthorityIncreased",
			getStructDecoder([["fields", getTupleDecoder([getCounterAuthorityIncreasedDecoder()])]])
		]
	]) as FixedSizeDecoder<CounterEvent>
}

export function getCounterEventCodec(): FixedSizeCodec<CounterEventArgs, CounterEvent> {
	return combineCodec(getCounterEventEncoder(), getCounterEventDecoder())
}

// Data Enum Helpers.
export function counterEvent(
	kind: "CounterInitialized",
	data: GetDiscriminatedUnionVariantContent<
		CounterEventArgs,
		"__kind",
		"CounterInitialized"
	>["fields"]
): GetDiscriminatedUnionVariant<CounterEventArgs, "__kind", "CounterInitialized">
export function counterEvent(
	kind: "CounterIncreased",
	data: GetDiscriminatedUnionVariantContent<
		CounterEventArgs,
		"__kind",
		"CounterIncreased"
	>["fields"]
): GetDiscriminatedUnionVariant<CounterEventArgs, "__kind", "CounterIncreased">
export function counterEvent(
	kind: "CounterAuthorityInitialized",
	data: GetDiscriminatedUnionVariantContent<
		CounterEventArgs,
		"__kind",
		"CounterAuthorityInitialized"
	>["fields"]
): GetDiscriminatedUnionVariant<CounterEventArgs, "__kind", "CounterAuthorityInitialized">
export function counterEvent(
	kind: "CounterAuthorityIncreased",
	data: GetDiscriminatedUnionVariantContent<
		CounterEventArgs,
		"__kind",
		"CounterAuthorityIncreased"
	>["fields"]
): GetDiscriminatedUnionVariant<CounterEventArgs, "__kind", "CounterAuthorityIncreased">
export function counterEvent<K extends CounterEventArgs["__kind"], Data>(kind: K, data?: Data) {
	return Array.isArray(data) ? { __kind: kind, fields: data } : { __kind: kind, ...(data ?? {}) }
}

export function isCounterEvent<K extends CounterEvent["__kind"]>(
	kind: K,
	value: CounterEvent
): value is CounterEvent & { __kind: K } {
	return value.__kind === kind
}
