/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type AccountMeta,
	type AccountSignerMeta,
	type Address,
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	fixDecoderSize,
	fixEncoderSize,
	getBytesDecoder,
	getBytesEncoder,
	getStructDecoder,
	getStructEncoder,
	getU8Decoder,
	getU8Encoder,
	type Instruction,
	type InstructionWithAccounts,
	type InstructionWithData,
	type ReadonlyAccount,
	type ReadonlySignerAccount,
	type ReadonlyUint8Array,
	SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
	SolanaError,
	type TransactionSigner,
	transformEncoder,
	type WritableAccount
} from "@solana/kit"
import { getAccountMetaFactory, type ResolvedInstructionAccount } from "@solana/program-client-core"
import { BASIC_MINT_PROGRAM_ADDRESS } from "../programs"

export const CREATE_MINT_DISCRIMINATOR = 0

export function getCreateMintDiscriminatorBytes() {
	return getU8Encoder().encode(CREATE_MINT_DISCRIMINATOR)
}

export type CreateMintInstruction<
	TProgram extends string = typeof BASIC_MINT_PROGRAM_ADDRESS,
	TAccountPayer extends string | AccountMeta<string> = string,
	TAccountMint extends string | AccountMeta<string> = string,
	TAccountTokenProgram extends
		| string
		| AccountMeta<string> = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
	TAccountSystemProgram extends string | AccountMeta<string> = "11111111111111111111111111111111",
	TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
	InstructionWithData<ReadonlyUint8Array> &
	InstructionWithAccounts<
		[
			TAccountPayer extends string
				? ReadonlySignerAccount<TAccountPayer> & AccountSignerMeta<TAccountPayer>
				: TAccountPayer,
			TAccountMint extends string ? WritableAccount<TAccountMint> : TAccountMint,
			TAccountTokenProgram extends string
				? ReadonlyAccount<TAccountTokenProgram>
				: TAccountTokenProgram,
			TAccountSystemProgram extends string
				? ReadonlyAccount<TAccountSystemProgram>
				: TAccountSystemProgram,
			...TRemainingAccounts
		]
	>

export type CreateMintInstructionData = {
	discriminator: number
	decimals: number
	name: ReadonlyUint8Array
	symbol: ReadonlyUint8Array
	uri: ReadonlyUint8Array
}

export type CreateMintInstructionDataArgs = {
	decimals: number
	name: ReadonlyUint8Array
	symbol: ReadonlyUint8Array
	uri: ReadonlyUint8Array
}

export function getCreateMintInstructionDataEncoder(): FixedSizeEncoder<CreateMintInstructionDataArgs> {
	return transformEncoder(
		getStructEncoder([
			["discriminator", getU8Encoder()],
			["decimals", getU8Encoder()],
			["name", fixEncoderSize(getBytesEncoder(), 32)],
			["symbol", fixEncoderSize(getBytesEncoder(), 8)],
			["uri", fixEncoderSize(getBytesEncoder(), 64)]
		]),
		value => ({ ...value, discriminator: CREATE_MINT_DISCRIMINATOR })
	)
}

export function getCreateMintInstructionDataDecoder(): FixedSizeDecoder<CreateMintInstructionData> {
	return getStructDecoder([
		["discriminator", getU8Decoder()],
		["decimals", getU8Decoder()],
		["name", fixDecoderSize(getBytesDecoder(), 32)],
		["symbol", fixDecoderSize(getBytesDecoder(), 8)],
		["uri", fixDecoderSize(getBytesDecoder(), 64)]
	])
}

export function getCreateMintInstructionDataCodec(): FixedSizeCodec<
	CreateMintInstructionDataArgs,
	CreateMintInstructionData
> {
	return combineCodec(getCreateMintInstructionDataEncoder(), getCreateMintInstructionDataDecoder())
}

export type CreateMintInput<
	TAccountPayer extends string = string,
	TAccountMint extends string = string,
	TAccountTokenProgram extends string = string,
	TAccountSystemProgram extends string = string
> = {
	/** The payer for the mint creation */
	payer: TransactionSigner<TAccountPayer>
	/** The mint account (PDA) */
	mint: Address<TAccountMint>
	/** Token-2022 program */
	tokenProgram?: Address<TAccountTokenProgram>
	/** System program */
	systemProgram?: Address<TAccountSystemProgram>
	decimals: CreateMintInstructionDataArgs["decimals"]
	name: CreateMintInstructionDataArgs["name"]
	symbol: CreateMintInstructionDataArgs["symbol"]
	uri: CreateMintInstructionDataArgs["uri"]
}

export function getCreateMintInstruction<
	TAccountPayer extends string,
	TAccountMint extends string,
	TAccountTokenProgram extends string,
	TAccountSystemProgram extends string,
	TProgramAddress extends Address = typeof BASIC_MINT_PROGRAM_ADDRESS
>(
	input: CreateMintInput<TAccountPayer, TAccountMint, TAccountTokenProgram, TAccountSystemProgram>,
	config?: { programAddress?: TProgramAddress }
): CreateMintInstruction<
	TProgramAddress,
	TAccountPayer,
	TAccountMint,
	TAccountTokenProgram,
	TAccountSystemProgram
> {
	// Program address.
	const programAddress = config?.programAddress ?? BASIC_MINT_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		payer: { value: input.payer ?? null, isWritable: false },
		mint: { value: input.mint ?? null, isWritable: true },
		tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
		systemProgram: { value: input.systemProgram ?? null, isWritable: false }
	}
	const accounts = originalAccounts as Record<
		keyof typeof originalAccounts,
		ResolvedInstructionAccount
	>

	// Original args.
	const args = { ...input }

	// Resolve default values.
	if (!accounts.tokenProgram.value) {
		accounts.tokenProgram.value =
			"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">
	}
	if (!accounts.systemProgram.value) {
		accounts.systemProgram.value =
			"11111111111111111111111111111111" as Address<"11111111111111111111111111111111">
	}

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta("payer", accounts.payer),
			getAccountMeta("mint", accounts.mint),
			getAccountMeta("tokenProgram", accounts.tokenProgram),
			getAccountMeta("systemProgram", accounts.systemProgram)
		],
		data: getCreateMintInstructionDataEncoder().encode(args as CreateMintInstructionDataArgs),
		programAddress
	} as CreateMintInstruction<
		TProgramAddress,
		TAccountPayer,
		TAccountMint,
		TAccountTokenProgram,
		TAccountSystemProgram
	>)
}

export type ParsedCreateMintInstruction<
	TProgram extends string = typeof BASIC_MINT_PROGRAM_ADDRESS,
	TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
	programAddress: Address<TProgram>
	accounts: {
		/** The payer for the mint creation */
		payer: TAccountMetas[0]
		/** The mint account (PDA) */
		mint: TAccountMetas[1]
		/** Token-2022 program */
		tokenProgram: TAccountMetas[2]
		/** System program */
		systemProgram: TAccountMetas[3]
	}
	data: CreateMintInstructionData
}

export function parseCreateMintInstruction<
	TProgram extends string,
	TAccountMetas extends readonly AccountMeta[]
>(
	instruction: Instruction<TProgram> &
		InstructionWithAccounts<TAccountMetas> &
		InstructionWithData<ReadonlyUint8Array>
): ParsedCreateMintInstruction<TProgram, TAccountMetas> {
	if (instruction.accounts.length < 4) {
		throw new SolanaError(SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS, {
			actualAccountMetas: instruction.accounts.length,
			expectedAccountMetas: 4
		})
	}
	let accountIndex = 0
	const getNextAccount = () => {
		const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!
		accountIndex += 1
		return accountMeta
	}
	return {
		programAddress: instruction.programAddress,
		accounts: {
			payer: getNextAccount(),
			mint: getNextAccount(),
			tokenProgram: getNextAccount(),
			systemProgram: getNextAccount()
		},
		data: getCreateMintInstructionDataDecoder().decode(instruction.data)
	}
}
