/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type AccountMeta,
	type AccountSignerMeta,
	type Address,
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	getStructDecoder,
	getStructEncoder,
	getU8Decoder,
	getU8Encoder,
	getU64Decoder,
	getU64Encoder,
	type Instruction,
	type InstructionWithAccounts,
	type InstructionWithData,
	type ReadonlyAccount,
	type ReadonlySignerAccount,
	type ReadonlyUint8Array,
	SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
	SolanaError,
	type TransactionSigner,
	transformEncoder,
	type WritableAccount
} from "@solana/kit"
import { getAccountMetaFactory, type ResolvedInstructionAccount } from "@solana/program-client-core"
import { BASIC_MINT_PROGRAM_ADDRESS } from "../programs"

export const TRANSFER_MINT_DISCRIMINATOR = 1

export function getTransferMintDiscriminatorBytes() {
	return getU8Encoder().encode(TRANSFER_MINT_DISCRIMINATOR)
}

export type TransferMintInstruction<
	TProgram extends string = typeof BASIC_MINT_PROGRAM_ADDRESS,
	TAccountFromTokenAccount extends string | AccountMeta<string> = string,
	TAccountMint extends string | AccountMeta<string> = string,
	TAccountToTokenAccount extends string | AccountMeta<string> = string,
	TAccountAuthority extends string | AccountMeta<string> = string,
	TAccountTokenProgram extends
		| string
		| AccountMeta<string> = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
	TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
	InstructionWithData<ReadonlyUint8Array> &
	InstructionWithAccounts<
		[
			TAccountFromTokenAccount extends string
				? WritableAccount<TAccountFromTokenAccount>
				: TAccountFromTokenAccount,
			TAccountMint extends string ? ReadonlyAccount<TAccountMint> : TAccountMint,
			TAccountToTokenAccount extends string
				? WritableAccount<TAccountToTokenAccount>
				: TAccountToTokenAccount,
			TAccountAuthority extends string
				? ReadonlySignerAccount<TAccountAuthority> & AccountSignerMeta<TAccountAuthority>
				: TAccountAuthority,
			TAccountTokenProgram extends string
				? ReadonlyAccount<TAccountTokenProgram>
				: TAccountTokenProgram,
			...TRemainingAccounts
		]
	>

export type TransferMintInstructionData = {
	discriminator: number
	amount: bigint
	decimals: number
}

export type TransferMintInstructionDataArgs = {
	amount: number | bigint
	decimals: number
}

export function getTransferMintInstructionDataEncoder(): FixedSizeEncoder<TransferMintInstructionDataArgs> {
	return transformEncoder(
		getStructEncoder([
			["discriminator", getU8Encoder()],
			["amount", getU64Encoder()],
			["decimals", getU8Encoder()]
		]),
		value => ({ ...value, discriminator: TRANSFER_MINT_DISCRIMINATOR })
	)
}

export function getTransferMintInstructionDataDecoder(): FixedSizeDecoder<TransferMintInstructionData> {
	return getStructDecoder([
		["discriminator", getU8Decoder()],
		["amount", getU64Decoder()],
		["decimals", getU8Decoder()]
	])
}

export function getTransferMintInstructionDataCodec(): FixedSizeCodec<
	TransferMintInstructionDataArgs,
	TransferMintInstructionData
> {
	return combineCodec(
		getTransferMintInstructionDataEncoder(),
		getTransferMintInstructionDataDecoder()
	)
}

export type TransferMintInput<
	TAccountFromTokenAccount extends string = string,
	TAccountMint extends string = string,
	TAccountToTokenAccount extends string = string,
	TAccountAuthority extends string = string,
	TAccountTokenProgram extends string = string
> = {
	/** Source token account */
	fromTokenAccount: Address<TAccountFromTokenAccount>
	/** The token mint */
	mint: Address<TAccountMint>
	/** Destination token account */
	toTokenAccount: Address<TAccountToTokenAccount>
	/** Authority/owner of the source token account */
	authority: TransactionSigner<TAccountAuthority>
	/** Token-2022 program */
	tokenProgram?: Address<TAccountTokenProgram>
	amount: TransferMintInstructionDataArgs["amount"]
	decimals: TransferMintInstructionDataArgs["decimals"]
}

export function getTransferMintInstruction<
	TAccountFromTokenAccount extends string,
	TAccountMint extends string,
	TAccountToTokenAccount extends string,
	TAccountAuthority extends string,
	TAccountTokenProgram extends string,
	TProgramAddress extends Address = typeof BASIC_MINT_PROGRAM_ADDRESS
>(
	input: TransferMintInput<
		TAccountFromTokenAccount,
		TAccountMint,
		TAccountToTokenAccount,
		TAccountAuthority,
		TAccountTokenProgram
	>,
	config?: { programAddress?: TProgramAddress }
): TransferMintInstruction<
	TProgramAddress,
	TAccountFromTokenAccount,
	TAccountMint,
	TAccountToTokenAccount,
	TAccountAuthority,
	TAccountTokenProgram
> {
	// Program address.
	const programAddress = config?.programAddress ?? BASIC_MINT_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		fromTokenAccount: {
			value: input.fromTokenAccount ?? null,
			isWritable: true
		},
		mint: { value: input.mint ?? null, isWritable: false },
		toTokenAccount: { value: input.toTokenAccount ?? null, isWritable: true },
		authority: { value: input.authority ?? null, isWritable: false },
		tokenProgram: { value: input.tokenProgram ?? null, isWritable: false }
	}
	const accounts = originalAccounts as Record<
		keyof typeof originalAccounts,
		ResolvedInstructionAccount
	>

	// Original args.
	const args = { ...input }

	// Resolve default values.
	if (!accounts.tokenProgram.value) {
		accounts.tokenProgram.value =
			"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">
	}

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta("fromTokenAccount", accounts.fromTokenAccount),
			getAccountMeta("mint", accounts.mint),
			getAccountMeta("toTokenAccount", accounts.toTokenAccount),
			getAccountMeta("authority", accounts.authority),
			getAccountMeta("tokenProgram", accounts.tokenProgram)
		],
		data: getTransferMintInstructionDataEncoder().encode(args as TransferMintInstructionDataArgs),
		programAddress
	} as TransferMintInstruction<
		TProgramAddress,
		TAccountFromTokenAccount,
		TAccountMint,
		TAccountToTokenAccount,
		TAccountAuthority,
		TAccountTokenProgram
	>)
}

export type ParsedTransferMintInstruction<
	TProgram extends string = typeof BASIC_MINT_PROGRAM_ADDRESS,
	TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
	programAddress: Address<TProgram>
	accounts: {
		/** Source token account */
		fromTokenAccount: TAccountMetas[0]
		/** The token mint */
		mint: TAccountMetas[1]
		/** Destination token account */
		toTokenAccount: TAccountMetas[2]
		/** Authority/owner of the source token account */
		authority: TAccountMetas[3]
		/** Token-2022 program */
		tokenProgram: TAccountMetas[4]
	}
	data: TransferMintInstructionData
}

export function parseTransferMintInstruction<
	TProgram extends string,
	TAccountMetas extends readonly AccountMeta[]
>(
	instruction: Instruction<TProgram> &
		InstructionWithAccounts<TAccountMetas> &
		InstructionWithData<ReadonlyUint8Array>
): ParsedTransferMintInstruction<TProgram, TAccountMetas> {
	if (instruction.accounts.length < 5) {
		throw new SolanaError(SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS, {
			actualAccountMetas: instruction.accounts.length,
			expectedAccountMetas: 5
		})
	}
	let accountIndex = 0
	const getNextAccount = () => {
		const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!
		accountIndex += 1
		return accountMeta
	}
	return {
		programAddress: instruction.programAddress,
		accounts: {
			fromTokenAccount: getNextAccount(),
			mint: getNextAccount(),
			toTokenAccount: getNextAccount(),
			authority: getNextAccount(),
			tokenProgram: getNextAccount()
		},
		data: getTransferMintInstructionDataDecoder().decode(instruction.data)
	}
}
