/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type AccountMeta,
	type AccountSignerMeta,
	type Address,
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	fixDecoderSize,
	fixEncoderSize,
	getBytesDecoder,
	getBytesEncoder,
	getStructDecoder,
	getStructEncoder,
	getU8Decoder,
	getU8Encoder,
	type Instruction,
	type InstructionWithAccounts,
	type InstructionWithData,
	type ReadonlyAccount,
	type ReadonlySignerAccount,
	type ReadonlyUint8Array,
	SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
	SolanaError,
	type TransactionSigner,
	transformEncoder,
	type WritableAccount
} from "@solana/kit"
import { getAccountMetaFactory, type ResolvedInstructionAccount } from "@solana/program-client-core"
import { FULL_SHANK_PROGRAM_ADDRESS } from "../programs"

export const CREATE_PROFILE_DISCRIMINATOR = 1

export function getCreateProfileDiscriminatorBytes() {
	return getU8Encoder().encode(CREATE_PROFILE_DISCRIMINATOR)
}

export type CreateProfileInstruction<
	TProgram extends string = typeof FULL_SHANK_PROGRAM_ADDRESS,
	TAccountPayer extends string | AccountMeta<string> = string,
	TAccountProfile extends string | AccountMeta<string> = string,
	TAccountReferrer extends string | AccountMeta<string> = string,
	TAccountSystemProgram extends string | AccountMeta<string> = "11111111111111111111111111111111",
	TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
	InstructionWithData<ReadonlyUint8Array> &
	InstructionWithAccounts<
		[
			TAccountPayer extends string
				? ReadonlySignerAccount<TAccountPayer> & AccountSignerMeta<TAccountPayer>
				: TAccountPayer,
			TAccountProfile extends string ? WritableAccount<TAccountProfile> : TAccountProfile,
			TAccountReferrer extends string ? ReadonlyAccount<TAccountReferrer> : TAccountReferrer,
			TAccountSystemProgram extends string
				? ReadonlyAccount<TAccountSystemProgram>
				: TAccountSystemProgram,
			...TRemainingAccounts
		]
	>

export type CreateProfileInstructionData = {
	discriminator: number
	username: ReadonlyUint8Array
}

export type CreateProfileInstructionDataArgs = { username: ReadonlyUint8Array }

export function getCreateProfileInstructionDataEncoder(): FixedSizeEncoder<CreateProfileInstructionDataArgs> {
	return transformEncoder(
		getStructEncoder([
			["discriminator", getU8Encoder()],
			["username", fixEncoderSize(getBytesEncoder(), 32)]
		]),
		value => ({ ...value, discriminator: CREATE_PROFILE_DISCRIMINATOR })
	)
}

export function getCreateProfileInstructionDataDecoder(): FixedSizeDecoder<CreateProfileInstructionData> {
	return getStructDecoder([
		["discriminator", getU8Decoder()],
		["username", fixDecoderSize(getBytesDecoder(), 32)]
	])
}

export function getCreateProfileInstructionDataCodec(): FixedSizeCodec<
	CreateProfileInstructionDataArgs,
	CreateProfileInstructionData
> {
	return combineCodec(
		getCreateProfileInstructionDataEncoder(),
		getCreateProfileInstructionDataDecoder()
	)
}

export type CreateProfileInput<
	TAccountPayer extends string = string,
	TAccountProfile extends string = string,
	TAccountReferrer extends string = string,
	TAccountSystemProgram extends string = string
> = {
	/** Fee payer; becomes the profile authority */
	payer: TransactionSigner<TAccountPayer>
	/** User profile PDA (seeds: ["profile", payer]) */
	profile: Address<TAccountProfile>
	/** Optional referrer profile — omit if not using referrals */
	referrer?: Address<TAccountReferrer>
	/** System program */
	systemProgram?: Address<TAccountSystemProgram>
	username: CreateProfileInstructionDataArgs["username"]
}

export function getCreateProfileInstruction<
	TAccountPayer extends string,
	TAccountProfile extends string,
	TAccountReferrer extends string,
	TAccountSystemProgram extends string,
	TProgramAddress extends Address = typeof FULL_SHANK_PROGRAM_ADDRESS
>(
	input: CreateProfileInput<
		TAccountPayer,
		TAccountProfile,
		TAccountReferrer,
		TAccountSystemProgram
	>,
	config?: { programAddress?: TProgramAddress }
): CreateProfileInstruction<
	TProgramAddress,
	TAccountPayer,
	TAccountProfile,
	TAccountReferrer,
	TAccountSystemProgram
> {
	// Program address.
	const programAddress = config?.programAddress ?? FULL_SHANK_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		payer: { value: input.payer ?? null, isWritable: false },
		profile: { value: input.profile ?? null, isWritable: true },
		referrer: { value: input.referrer ?? null, isWritable: false },
		systemProgram: { value: input.systemProgram ?? null, isWritable: false }
	}
	const accounts = originalAccounts as Record<
		keyof typeof originalAccounts,
		ResolvedInstructionAccount
	>

	// Original args.
	const args = { ...input }

	// Resolve default values.
	if (!accounts.systemProgram.value) {
		accounts.systemProgram.value =
			"11111111111111111111111111111111" as Address<"11111111111111111111111111111111">
	}

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta("payer", accounts.payer),
			getAccountMeta("profile", accounts.profile),
			getAccountMeta("referrer", accounts.referrer),
			getAccountMeta("systemProgram", accounts.systemProgram)
		],
		data: getCreateProfileInstructionDataEncoder().encode(args as CreateProfileInstructionDataArgs),
		programAddress
	} as CreateProfileInstruction<
		TProgramAddress,
		TAccountPayer,
		TAccountProfile,
		TAccountReferrer,
		TAccountSystemProgram
	>)
}

export type ParsedCreateProfileInstruction<
	TProgram extends string = typeof FULL_SHANK_PROGRAM_ADDRESS,
	TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
	programAddress: Address<TProgram>
	accounts: {
		/** Fee payer; becomes the profile authority */
		payer: TAccountMetas[0]
		/** User profile PDA (seeds: ["profile", payer]) */
		profile: TAccountMetas[1]
		/** Optional referrer profile — omit if not using referrals */
		referrer?: TAccountMetas[2] | undefined
		/** System program */
		systemProgram: TAccountMetas[3]
	}
	data: CreateProfileInstructionData
}

export function parseCreateProfileInstruction<
	TProgram extends string,
	TAccountMetas extends readonly AccountMeta[]
>(
	instruction: Instruction<TProgram> &
		InstructionWithAccounts<TAccountMetas> &
		InstructionWithData<ReadonlyUint8Array>
): ParsedCreateProfileInstruction<TProgram, TAccountMetas> {
	if (instruction.accounts.length < 4) {
		throw new SolanaError(SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS, {
			actualAccountMetas: instruction.accounts.length,
			expectedAccountMetas: 4
		})
	}
	let accountIndex = 0
	const getNextAccount = () => {
		const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!
		accountIndex += 1
		return accountMeta
	}
	const getNextOptionalAccount = () => {
		const accountMeta = getNextAccount()
		return accountMeta.address === FULL_SHANK_PROGRAM_ADDRESS ? undefined : accountMeta
	}
	return {
		programAddress: instruction.programAddress,
		accounts: {
			payer: getNextAccount(),
			profile: getNextAccount(),
			referrer: getNextOptionalAccount(),
			systemProgram: getNextAccount()
		},
		data: getCreateProfileInstructionDataDecoder().decode(instruction.data)
	}
}
