/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type AccountMeta,
	type AccountSignerMeta,
	type Address,
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	getStructDecoder,
	getStructEncoder,
	getU8Decoder,
	getU8Encoder,
	type Instruction,
	type InstructionWithAccounts,
	type InstructionWithData,
	type ReadonlyAccount,
	type ReadonlySignerAccount,
	type ReadonlyUint8Array,
	SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
	SolanaError,
	type TransactionSigner,
	transformEncoder,
	type WritableAccount
} from "@solana/kit"
import { getAccountMetaFactory, type ResolvedInstructionAccount } from "@solana/program-client-core"
import { FULL_SHANK_PROGRAM_ADDRESS } from "../programs"

export const DELETE_POST_DISCRIMINATOR = 4

export function getDeletePostDiscriminatorBytes() {
	return getU8Encoder().encode(DELETE_POST_DISCRIMINATOR)
}

export type DeletePostInstruction<
	TProgram extends string = typeof FULL_SHANK_PROGRAM_ADDRESS,
	TAccountAuthority extends string | AccountMeta<string> = string,
	TAccountPost extends string | AccountMeta<string> = string,
	TAccountRefundTo extends string | AccountMeta<string> = string,
	TAccountConfig extends string | AccountMeta<string> = string,
	TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
	InstructionWithData<ReadonlyUint8Array> &
	InstructionWithAccounts<
		[
			TAccountAuthority extends string
				? ReadonlySignerAccount<TAccountAuthority> & AccountSignerMeta<TAccountAuthority>
				: TAccountAuthority,
			TAccountPost extends string ? WritableAccount<TAccountPost> : TAccountPost,
			TAccountRefundTo extends string ? WritableAccount<TAccountRefundTo> : TAccountRefundTo,
			TAccountConfig extends string ? ReadonlyAccount<TAccountConfig> : TAccountConfig,
			...TRemainingAccounts
		]
	>

export type DeletePostInstructionData = { discriminator: number }

export type DeletePostInstructionDataArgs = {}

export function getDeletePostInstructionDataEncoder(): FixedSizeEncoder<DeletePostInstructionDataArgs> {
	return transformEncoder(getStructEncoder([["discriminator", getU8Encoder()]]), value => ({
		...value,
		discriminator: DELETE_POST_DISCRIMINATOR
	}))
}

export function getDeletePostInstructionDataDecoder(): FixedSizeDecoder<DeletePostInstructionData> {
	return getStructDecoder([["discriminator", getU8Decoder()]])
}

export function getDeletePostInstructionDataCodec(): FixedSizeCodec<
	DeletePostInstructionDataArgs,
	DeletePostInstructionData
> {
	return combineCodec(getDeletePostInstructionDataEncoder(), getDeletePostInstructionDataDecoder())
}

export type DeletePostInput<
	TAccountAuthority extends string = string,
	TAccountPost extends string = string,
	TAccountRefundTo extends string = string,
	TAccountConfig extends string = string
> = {
	/** Author or admin initiating the deletion */
	authority: TransactionSigner<TAccountAuthority>
	/** The post PDA to close */
	post: Address<TAccountPost>
	/** Destination for the reclaimed lamports */
	refundTo: Address<TAccountRefundTo>
	/** Board config — required only when the caller is the admin */
	config?: Address<TAccountConfig>
}

export function getDeletePostInstruction<
	TAccountAuthority extends string,
	TAccountPost extends string,
	TAccountRefundTo extends string,
	TAccountConfig extends string,
	TProgramAddress extends Address = typeof FULL_SHANK_PROGRAM_ADDRESS
>(
	input: DeletePostInput<TAccountAuthority, TAccountPost, TAccountRefundTo, TAccountConfig>,
	config?: { programAddress?: TProgramAddress }
): DeletePostInstruction<
	TProgramAddress,
	TAccountAuthority,
	TAccountPost,
	TAccountRefundTo,
	TAccountConfig
> {
	// Program address.
	const programAddress = config?.programAddress ?? FULL_SHANK_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		authority: { value: input.authority ?? null, isWritable: false },
		post: { value: input.post ?? null, isWritable: true },
		refundTo: { value: input.refundTo ?? null, isWritable: true },
		config: { value: input.config ?? null, isWritable: false }
	}
	const accounts = originalAccounts as Record<
		keyof typeof originalAccounts,
		ResolvedInstructionAccount
	>

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta("authority", accounts.authority),
			getAccountMeta("post", accounts.post),
			getAccountMeta("refundTo", accounts.refundTo),
			getAccountMeta("config", accounts.config)
		],
		data: getDeletePostInstructionDataEncoder().encode({}),
		programAddress
	} as DeletePostInstruction<
		TProgramAddress,
		TAccountAuthority,
		TAccountPost,
		TAccountRefundTo,
		TAccountConfig
	>)
}

export type ParsedDeletePostInstruction<
	TProgram extends string = typeof FULL_SHANK_PROGRAM_ADDRESS,
	TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
	programAddress: Address<TProgram>
	accounts: {
		/** Author or admin initiating the deletion */
		authority: TAccountMetas[0]
		/** The post PDA to close */
		post: TAccountMetas[1]
		/** Destination for the reclaimed lamports */
		refundTo: TAccountMetas[2]
		/** Board config — required only when the caller is the admin */
		config?: TAccountMetas[3] | undefined
	}
	data: DeletePostInstructionData
}

export function parseDeletePostInstruction<
	TProgram extends string,
	TAccountMetas extends readonly AccountMeta[]
>(
	instruction: Instruction<TProgram> &
		InstructionWithAccounts<TAccountMetas> &
		InstructionWithData<ReadonlyUint8Array>
): ParsedDeletePostInstruction<TProgram, TAccountMetas> {
	if (instruction.accounts.length < 4) {
		throw new SolanaError(SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS, {
			actualAccountMetas: instruction.accounts.length,
			expectedAccountMetas: 4
		})
	}
	let accountIndex = 0
	const getNextAccount = () => {
		const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!
		accountIndex += 1
		return accountMeta
	}
	const getNextOptionalAccount = () => {
		const accountMeta = getNextAccount()
		return accountMeta.address === FULL_SHANK_PROGRAM_ADDRESS ? undefined : accountMeta
	}
	return {
		programAddress: instruction.programAddress,
		accounts: {
			authority: getNextAccount(),
			post: getNextAccount(),
			refundTo: getNextAccount(),
			config: getNextOptionalAccount()
		},
		data: getDeletePostInstructionDataDecoder().decode(instruction.data)
	}
}
