/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

export * from "./createProfile"
export * from "./deletePost"
export * from "./initBoard"
export * from "./postMessage"
export * from "./suspendProfile"
export * from "./updateUsername"
