/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type AccountMeta,
	type AccountSignerMeta,
	type Address,
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	getStructDecoder,
	getStructEncoder,
	getU8Decoder,
	getU8Encoder,
	getU64Decoder,
	getU64Encoder,
	type Instruction,
	type InstructionWithAccounts,
	type InstructionWithData,
	type ReadonlyAccount,
	type ReadonlySignerAccount,
	type ReadonlyUint8Array,
	SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
	SolanaError,
	type TransactionSigner,
	transformEncoder,
	type WritableAccount
} from "@solana/kit"
import { getAccountMetaFactory, type ResolvedInstructionAccount } from "@solana/program-client-core"
import { FULL_SHANK_PROGRAM_ADDRESS } from "../programs"

export const INIT_BOARD_DISCRIMINATOR = 0

export function getInitBoardDiscriminatorBytes() {
	return getU8Encoder().encode(INIT_BOARD_DISCRIMINATOR)
}

export type InitBoardInstruction<
	TProgram extends string = typeof FULL_SHANK_PROGRAM_ADDRESS,
	TAccountAdmin extends string | AccountMeta<string> = string,
	TAccountConfig extends string | AccountMeta<string> = string,
	TAccountSystemProgram extends string | AccountMeta<string> = "11111111111111111111111111111111",
	TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
	InstructionWithData<ReadonlyUint8Array> &
	InstructionWithAccounts<
		[
			TAccountAdmin extends string
				? ReadonlySignerAccount<TAccountAdmin> & AccountSignerMeta<TAccountAdmin>
				: TAccountAdmin,
			TAccountConfig extends string ? WritableAccount<TAccountConfig> : TAccountConfig,
			TAccountSystemProgram extends string
				? ReadonlyAccount<TAccountSystemProgram>
				: TAccountSystemProgram,
			...TRemainingAccounts
		]
	>

export type InitBoardInstructionData = {
	discriminator: number
	postFee: bigint
}

export type InitBoardInstructionDataArgs = { postFee: number | bigint }

export function getInitBoardInstructionDataEncoder(): FixedSizeEncoder<InitBoardInstructionDataArgs> {
	return transformEncoder(
		getStructEncoder([
			["discriminator", getU8Encoder()],
			["postFee", getU64Encoder()]
		]),
		value => ({ ...value, discriminator: INIT_BOARD_DISCRIMINATOR })
	)
}

export function getInitBoardInstructionDataDecoder(): FixedSizeDecoder<InitBoardInstructionData> {
	return getStructDecoder([
		["discriminator", getU8Decoder()],
		["postFee", getU64Decoder()]
	])
}

export function getInitBoardInstructionDataCodec(): FixedSizeCodec<
	InitBoardInstructionDataArgs,
	InitBoardInstructionData
> {
	return combineCodec(getInitBoardInstructionDataEncoder(), getInitBoardInstructionDataDecoder())
}

export type InitBoardInput<
	TAccountAdmin extends string = string,
	TAccountConfig extends string = string,
	TAccountSystemProgram extends string = string
> = {
	/** Board administrator; pays for config creation */
	admin: TransactionSigner<TAccountAdmin>
	/** Board config PDA (seeds: ["board"]) */
	config: Address<TAccountConfig>
	/** System program */
	systemProgram?: Address<TAccountSystemProgram>
	postFee: InitBoardInstructionDataArgs["postFee"]
}

export function getInitBoardInstruction<
	TAccountAdmin extends string,
	TAccountConfig extends string,
	TAccountSystemProgram extends string,
	TProgramAddress extends Address = typeof FULL_SHANK_PROGRAM_ADDRESS
>(
	input: InitBoardInput<TAccountAdmin, TAccountConfig, TAccountSystemProgram>,
	config?: { programAddress?: TProgramAddress }
): InitBoardInstruction<TProgramAddress, TAccountAdmin, TAccountConfig, TAccountSystemProgram> {
	// Program address.
	const programAddress = config?.programAddress ?? FULL_SHANK_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		admin: { value: input.admin ?? null, isWritable: false },
		config: { value: input.config ?? null, isWritable: true },
		systemProgram: { value: input.systemProgram ?? null, isWritable: false }
	}
	const accounts = originalAccounts as Record<
		keyof typeof originalAccounts,
		ResolvedInstructionAccount
	>

	// Original args.
	const args = { ...input }

	// Resolve default values.
	if (!accounts.systemProgram.value) {
		accounts.systemProgram.value =
			"11111111111111111111111111111111" as Address<"11111111111111111111111111111111">
	}

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta("admin", accounts.admin),
			getAccountMeta("config", accounts.config),
			getAccountMeta("systemProgram", accounts.systemProgram)
		],
		data: getInitBoardInstructionDataEncoder().encode(args as InitBoardInstructionDataArgs),
		programAddress
	} as InitBoardInstruction<TProgramAddress, TAccountAdmin, TAccountConfig, TAccountSystemProgram>)
}

export type ParsedInitBoardInstruction<
	TProgram extends string = typeof FULL_SHANK_PROGRAM_ADDRESS,
	TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
	programAddress: Address<TProgram>
	accounts: {
		/** Board administrator; pays for config creation */
		admin: TAccountMetas[0]
		/** Board config PDA (seeds: ["board"]) */
		config: TAccountMetas[1]
		/** System program */
		systemProgram: TAccountMetas[2]
	}
	data: InitBoardInstructionData
}

export function parseInitBoardInstruction<
	TProgram extends string,
	TAccountMetas extends readonly AccountMeta[]
>(
	instruction: Instruction<TProgram> &
		InstructionWithAccounts<TAccountMetas> &
		InstructionWithData<ReadonlyUint8Array>
): ParsedInitBoardInstruction<TProgram, TAccountMetas> {
	if (instruction.accounts.length < 3) {
		throw new SolanaError(SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS, {
			actualAccountMetas: instruction.accounts.length,
			expectedAccountMetas: 3
		})
	}
	let accountIndex = 0
	const getNextAccount = () => {
		const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!
		accountIndex += 1
		return accountMeta
	}
	return {
		programAddress: instruction.programAddress,
		accounts: {
			admin: getNextAccount(),
			config: getNextAccount(),
			systemProgram: getNextAccount()
		},
		data: getInitBoardInstructionDataDecoder().decode(instruction.data)
	}
}
