/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type AccountMeta,
	type AccountSignerMeta,
	type Address,
	type Codec,
	combineCodec,
	type Decoder,
	type Encoder,
	fixDecoderSize,
	fixEncoderSize,
	getBytesDecoder,
	getBytesEncoder,
	getOptionDecoder,
	getOptionEncoder,
	getStructDecoder,
	getStructEncoder,
	getU8Decoder,
	getU8Encoder,
	type Instruction,
	type InstructionWithAccounts,
	type InstructionWithData,
	type Option,
	type OptionOrNullable,
	type ReadonlyAccount,
	type ReadonlySignerAccount,
	type ReadonlyUint8Array,
	SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
	SolanaError,
	type TransactionSigner,
	transformEncoder,
	type WritableAccount
} from "@solana/kit"
import { getAccountMetaFactory, type ResolvedInstructionAccount } from "@solana/program-client-core"
import { FULL_SHANK_PROGRAM_ADDRESS } from "../programs"

export const POST_MESSAGE_DISCRIMINATOR = 2

export function getPostMessageDiscriminatorBytes() {
	return getU8Encoder().encode(POST_MESSAGE_DISCRIMINATOR)
}

export type PostMessageInstruction<
	TProgram extends string = typeof FULL_SHANK_PROGRAM_ADDRESS,
	TAccountAuthor extends string | AccountMeta<string> = string,
	TAccountProfile extends string | AccountMeta<string> = string,
	TAccountPost extends string | AccountMeta<string> = string,
	TAccountSystemProgram extends string | AccountMeta<string> = "11111111111111111111111111111111",
	TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
	InstructionWithData<ReadonlyUint8Array> &
	InstructionWithAccounts<
		[
			TAccountAuthor extends string
				? ReadonlySignerAccount<TAccountAuthor> & AccountSignerMeta<TAccountAuthor>
				: TAccountAuthor,
			TAccountProfile extends string ? WritableAccount<TAccountProfile> : TAccountProfile,
			TAccountPost extends string ? WritableAccount<TAccountPost> : TAccountPost,
			TAccountSystemProgram extends string
				? ReadonlyAccount<TAccountSystemProgram>
				: TAccountSystemProgram,
			...TRemainingAccounts
		]
	>

export type PostMessageInstructionData = {
	discriminator: number
	content: ReadonlyUint8Array
	replyTo: Option<ReadonlyUint8Array>
}

export type PostMessageInstructionDataArgs = {
	content: ReadonlyUint8Array
	replyTo: OptionOrNullable<ReadonlyUint8Array>
}

export function getPostMessageInstructionDataEncoder(): Encoder<PostMessageInstructionDataArgs> {
	return transformEncoder(
		getStructEncoder([
			["discriminator", getU8Encoder()],
			["content", fixEncoderSize(getBytesEncoder(), 128)],
			["replyTo", getOptionEncoder(fixEncoderSize(getBytesEncoder(), 32))]
		]),
		value => ({ ...value, discriminator: POST_MESSAGE_DISCRIMINATOR })
	)
}

export function getPostMessageInstructionDataDecoder(): Decoder<PostMessageInstructionData> {
	return getStructDecoder([
		["discriminator", getU8Decoder()],
		["content", fixDecoderSize(getBytesDecoder(), 128)],
		["replyTo", getOptionDecoder(fixDecoderSize(getBytesDecoder(), 32))]
	])
}

export function getPostMessageInstructionDataCodec(): Codec<
	PostMessageInstructionDataArgs,
	PostMessageInstructionData
> {
	return combineCodec(
		getPostMessageInstructionDataEncoder(),
		getPostMessageInstructionDataDecoder()
	)
}

export type PostMessageInput<
	TAccountAuthor extends string = string,
	TAccountProfile extends string = string,
	TAccountPost extends string = string,
	TAccountSystemProgram extends string = string
> = {
	/** Message author */
	author: TransactionSigner<TAccountAuthor>
	/** Author's profile PDA */
	profile: Address<TAccountProfile>
	/** New post PDA (seeds: ["post", author, post_count]) */
	post: Address<TAccountPost>
	/** System program */
	systemProgram?: Address<TAccountSystemProgram>
	content: PostMessageInstructionDataArgs["content"]
	replyTo: PostMessageInstructionDataArgs["replyTo"]
}

export function getPostMessageInstruction<
	TAccountAuthor extends string,
	TAccountProfile extends string,
	TAccountPost extends string,
	TAccountSystemProgram extends string,
	TProgramAddress extends Address = typeof FULL_SHANK_PROGRAM_ADDRESS
>(
	input: PostMessageInput<TAccountAuthor, TAccountProfile, TAccountPost, TAccountSystemProgram>,
	config?: { programAddress?: TProgramAddress }
): PostMessageInstruction<
	TProgramAddress,
	TAccountAuthor,
	TAccountProfile,
	TAccountPost,
	TAccountSystemProgram
> {
	// Program address.
	const programAddress = config?.programAddress ?? FULL_SHANK_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		author: { value: input.author ?? null, isWritable: false },
		profile: { value: input.profile ?? null, isWritable: true },
		post: { value: input.post ?? null, isWritable: true },
		systemProgram: { value: input.systemProgram ?? null, isWritable: false }
	}
	const accounts = originalAccounts as Record<
		keyof typeof originalAccounts,
		ResolvedInstructionAccount
	>

	// Original args.
	const args = { ...input }

	// Resolve default values.
	if (!accounts.systemProgram.value) {
		accounts.systemProgram.value =
			"11111111111111111111111111111111" as Address<"11111111111111111111111111111111">
	}

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta("author", accounts.author),
			getAccountMeta("profile", accounts.profile),
			getAccountMeta("post", accounts.post),
			getAccountMeta("systemProgram", accounts.systemProgram)
		],
		data: getPostMessageInstructionDataEncoder().encode(args as PostMessageInstructionDataArgs),
		programAddress
	} as PostMessageInstruction<
		TProgramAddress,
		TAccountAuthor,
		TAccountProfile,
		TAccountPost,
		TAccountSystemProgram
	>)
}

export type ParsedPostMessageInstruction<
	TProgram extends string = typeof FULL_SHANK_PROGRAM_ADDRESS,
	TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
	programAddress: Address<TProgram>
	accounts: {
		/** Message author */
		author: TAccountMetas[0]
		/** Author's profile PDA */
		profile: TAccountMetas[1]
		/** New post PDA (seeds: ["post", author, post_count]) */
		post: TAccountMetas[2]
		/** System program */
		systemProgram: TAccountMetas[3]
	}
	data: PostMessageInstructionData
}

export function parsePostMessageInstruction<
	TProgram extends string,
	TAccountMetas extends readonly AccountMeta[]
>(
	instruction: Instruction<TProgram> &
		InstructionWithAccounts<TAccountMetas> &
		InstructionWithData<ReadonlyUint8Array>
): ParsedPostMessageInstruction<TProgram, TAccountMetas> {
	if (instruction.accounts.length < 4) {
		throw new SolanaError(SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS, {
			actualAccountMetas: instruction.accounts.length,
			expectedAccountMetas: 4
		})
	}
	let accountIndex = 0
	const getNextAccount = () => {
		const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!
		accountIndex += 1
		return accountMeta
	}
	return {
		programAddress: instruction.programAddress,
		accounts: {
			author: getNextAccount(),
			profile: getNextAccount(),
			post: getNextAccount(),
			systemProgram: getNextAccount()
		},
		data: getPostMessageInstructionDataDecoder().decode(instruction.data)
	}
}
