/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type AccountMeta,
	type AccountSignerMeta,
	type Address,
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	getStructDecoder,
	getStructEncoder,
	getU8Decoder,
	getU8Encoder,
	type Instruction,
	type InstructionWithAccounts,
	type InstructionWithData,
	type ReadonlyAccount,
	type ReadonlySignerAccount,
	type ReadonlyUint8Array,
	SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
	SolanaError,
	type TransactionSigner,
	transformEncoder,
	type WritableAccount
} from "@solana/kit"
import { getAccountMetaFactory, type ResolvedInstructionAccount } from "@solana/program-client-core"
import { FULL_SHANK_PROGRAM_ADDRESS } from "../programs"

export const SUSPEND_PROFILE_DISCRIMINATOR = 5

export function getSuspendProfileDiscriminatorBytes() {
	return getU8Encoder().encode(SUSPEND_PROFILE_DISCRIMINATOR)
}

export type SuspendProfileInstruction<
	TProgram extends string = typeof FULL_SHANK_PROGRAM_ADDRESS,
	TAccountAdmin extends string | AccountMeta<string> = string,
	TAccountConfig extends string | AccountMeta<string> = string,
	TAccountProfile extends string | AccountMeta<string> = string,
	TAccountCoAdmin extends string | AccountMeta<string> = string,
	TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
	InstructionWithData<ReadonlyUint8Array> &
	InstructionWithAccounts<
		[
			TAccountAdmin extends string
				? ReadonlySignerAccount<TAccountAdmin> & AccountSignerMeta<TAccountAdmin>
				: TAccountAdmin,
			TAccountConfig extends string ? WritableAccount<TAccountConfig> : TAccountConfig,
			TAccountProfile extends string ? WritableAccount<TAccountProfile> : TAccountProfile,
			TAccountCoAdmin extends string ? ReadonlyAccount<TAccountCoAdmin> : TAccountCoAdmin,
			...TRemainingAccounts
		]
	>

export type SuspendProfileInstructionData = { discriminator: number }

export type SuspendProfileInstructionDataArgs = {}

export function getSuspendProfileInstructionDataEncoder(): FixedSizeEncoder<SuspendProfileInstructionDataArgs> {
	return transformEncoder(getStructEncoder([["discriminator", getU8Encoder()]]), value => ({
		...value,
		discriminator: SUSPEND_PROFILE_DISCRIMINATOR
	}))
}

export function getSuspendProfileInstructionDataDecoder(): FixedSizeDecoder<SuspendProfileInstructionData> {
	return getStructDecoder([["discriminator", getU8Decoder()]])
}

export function getSuspendProfileInstructionDataCodec(): FixedSizeCodec<
	SuspendProfileInstructionDataArgs,
	SuspendProfileInstructionData
> {
	return combineCodec(
		getSuspendProfileInstructionDataEncoder(),
		getSuspendProfileInstructionDataDecoder()
	)
}

export type SuspendProfileInput<
	TAccountAdmin extends string = string,
	TAccountConfig extends string = string,
	TAccountProfile extends string = string,
	TAccountCoAdmin extends string = string
> = {
	/** Board administrator */
	admin: TransactionSigner<TAccountAdmin>
	/** Board config PDA (validates admin key) */
	config: Address<TAccountConfig>
	/** User profile to suspend */
	profile: Address<TAccountProfile>
	/** Optional second admin co-signer for governance */
	coAdmin: Address<TAccountCoAdmin> | TransactionSigner<TAccountCoAdmin>
}

export function getSuspendProfileInstruction<
	TAccountAdmin extends string,
	TAccountConfig extends string,
	TAccountProfile extends string,
	TAccountCoAdmin extends string,
	TProgramAddress extends Address = typeof FULL_SHANK_PROGRAM_ADDRESS
>(
	input: SuspendProfileInput<TAccountAdmin, TAccountConfig, TAccountProfile, TAccountCoAdmin>,
	config?: { programAddress?: TProgramAddress }
): SuspendProfileInstruction<
	TProgramAddress,
	TAccountAdmin,
	TAccountConfig,
	TAccountProfile,
	(typeof input)["coAdmin"] extends TransactionSigner<TAccountCoAdmin>
		? ReadonlySignerAccount<TAccountCoAdmin> & AccountSignerMeta<TAccountCoAdmin>
		: TAccountCoAdmin
> {
	// Program address.
	const programAddress = config?.programAddress ?? FULL_SHANK_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		admin: { value: input.admin ?? null, isWritable: false },
		config: { value: input.config ?? null, isWritable: true },
		profile: { value: input.profile ?? null, isWritable: true },
		coAdmin: { value: input.coAdmin ?? null, isWritable: false }
	}
	const accounts = originalAccounts as Record<
		keyof typeof originalAccounts,
		ResolvedInstructionAccount
	>

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta("admin", accounts.admin),
			getAccountMeta("config", accounts.config),
			getAccountMeta("profile", accounts.profile),
			getAccountMeta("coAdmin", accounts.coAdmin)
		],
		data: getSuspendProfileInstructionDataEncoder().encode({}),
		programAddress
	} as SuspendProfileInstruction<
		TProgramAddress,
		TAccountAdmin,
		TAccountConfig,
		TAccountProfile,
		(typeof input)["coAdmin"] extends TransactionSigner<TAccountCoAdmin>
			? ReadonlySignerAccount<TAccountCoAdmin> & AccountSignerMeta<TAccountCoAdmin>
			: TAccountCoAdmin
	>)
}

export type ParsedSuspendProfileInstruction<
	TProgram extends string = typeof FULL_SHANK_PROGRAM_ADDRESS,
	TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
	programAddress: Address<TProgram>
	accounts: {
		/** Board administrator */
		admin: TAccountMetas[0]
		/** Board config PDA (validates admin key) */
		config: TAccountMetas[1]
		/** User profile to suspend */
		profile: TAccountMetas[2]
		/** Optional second admin co-signer for governance */
		coAdmin: TAccountMetas[3]
	}
	data: SuspendProfileInstructionData
}

export function parseSuspendProfileInstruction<
	TProgram extends string,
	TAccountMetas extends readonly AccountMeta[]
>(
	instruction: Instruction<TProgram> &
		InstructionWithAccounts<TAccountMetas> &
		InstructionWithData<ReadonlyUint8Array>
): ParsedSuspendProfileInstruction<TProgram, TAccountMetas> {
	if (instruction.accounts.length < 4) {
		throw new SolanaError(SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS, {
			actualAccountMetas: instruction.accounts.length,
			expectedAccountMetas: 4
		})
	}
	let accountIndex = 0
	const getNextAccount = () => {
		const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!
		accountIndex += 1
		return accountMeta
	}
	return {
		programAddress: instruction.programAddress,
		accounts: {
			admin: getNextAccount(),
			config: getNextAccount(),
			profile: getNextAccount(),
			coAdmin: getNextAccount()
		},
		data: getSuspendProfileInstructionDataDecoder().decode(instruction.data)
	}
}
