/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type AccountMeta,
	type AccountSignerMeta,
	type Address,
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	fixDecoderSize,
	fixEncoderSize,
	getBytesDecoder,
	getBytesEncoder,
	getStructDecoder,
	getStructEncoder,
	getU8Decoder,
	getU8Encoder,
	type Instruction,
	type InstructionWithAccounts,
	type InstructionWithData,
	type ReadonlySignerAccount,
	type ReadonlyUint8Array,
	SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
	SolanaError,
	type TransactionSigner,
	transformEncoder,
	type WritableAccount
} from "@solana/kit"
import { getAccountMetaFactory, type ResolvedInstructionAccount } from "@solana/program-client-core"
import { FULL_SHANK_PROGRAM_ADDRESS } from "../programs"

export const UPDATE_USERNAME_DISCRIMINATOR = 3

export function getUpdateUsernameDiscriminatorBytes() {
	return getU8Encoder().encode(UPDATE_USERNAME_DISCRIMINATOR)
}

export type UpdateUsernameInstruction<
	TProgram extends string = typeof FULL_SHANK_PROGRAM_ADDRESS,
	TAccountAuthority extends string | AccountMeta<string> = string,
	TAccountProfile extends string | AccountMeta<string> = string,
	TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
	InstructionWithData<ReadonlyUint8Array> &
	InstructionWithAccounts<
		[
			TAccountAuthority extends string
				? ReadonlySignerAccount<TAccountAuthority> & AccountSignerMeta<TAccountAuthority>
				: TAccountAuthority,
			TAccountProfile extends string ? WritableAccount<TAccountProfile> : TAccountProfile,
			...TRemainingAccounts
		]
	>

export type UpdateUsernameInstructionData = {
	discriminator: number
	username: ReadonlyUint8Array
}

export type UpdateUsernameInstructionDataArgs = {
	username: ReadonlyUint8Array
}

export function getUpdateUsernameInstructionDataEncoder(): FixedSizeEncoder<UpdateUsernameInstructionDataArgs> {
	return transformEncoder(
		getStructEncoder([
			["discriminator", getU8Encoder()],
			["username", fixEncoderSize(getBytesEncoder(), 32)]
		]),
		value => ({ ...value, discriminator: UPDATE_USERNAME_DISCRIMINATOR })
	)
}

export function getUpdateUsernameInstructionDataDecoder(): FixedSizeDecoder<UpdateUsernameInstructionData> {
	return getStructDecoder([
		["discriminator", getU8Decoder()],
		["username", fixDecoderSize(getBytesDecoder(), 32)]
	])
}

export function getUpdateUsernameInstructionDataCodec(): FixedSizeCodec<
	UpdateUsernameInstructionDataArgs,
	UpdateUsernameInstructionData
> {
	return combineCodec(
		getUpdateUsernameInstructionDataEncoder(),
		getUpdateUsernameInstructionDataDecoder()
	)
}

export type UpdateUsernameInput<
	TAccountAuthority extends string = string,
	TAccountProfile extends string = string
> = {
	/** Profile authority (owner) */
	authority: TransactionSigner<TAccountAuthority>
	/** User profile PDA to update */
	profile: Address<TAccountProfile>
	username: UpdateUsernameInstructionDataArgs["username"]
}

export function getUpdateUsernameInstruction<
	TAccountAuthority extends string,
	TAccountProfile extends string,
	TProgramAddress extends Address = typeof FULL_SHANK_PROGRAM_ADDRESS
>(
	input: UpdateUsernameInput<TAccountAuthority, TAccountProfile>,
	config?: { programAddress?: TProgramAddress }
): UpdateUsernameInstruction<TProgramAddress, TAccountAuthority, TAccountProfile> {
	// Program address.
	const programAddress = config?.programAddress ?? FULL_SHANK_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		authority: { value: input.authority ?? null, isWritable: false },
		profile: { value: input.profile ?? null, isWritable: true }
	}
	const accounts = originalAccounts as Record<
		keyof typeof originalAccounts,
		ResolvedInstructionAccount
	>

	// Original args.
	const args = { ...input }

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta("authority", accounts.authority),
			getAccountMeta("profile", accounts.profile)
		],
		data: getUpdateUsernameInstructionDataEncoder().encode(
			args as UpdateUsernameInstructionDataArgs
		),
		programAddress
	} as UpdateUsernameInstruction<TProgramAddress, TAccountAuthority, TAccountProfile>)
}

export type ParsedUpdateUsernameInstruction<
	TProgram extends string = typeof FULL_SHANK_PROGRAM_ADDRESS,
	TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
	programAddress: Address<TProgram>
	accounts: {
		/** Profile authority (owner) */
		authority: TAccountMetas[0]
		/** User profile PDA to update */
		profile: TAccountMetas[1]
	}
	data: UpdateUsernameInstructionData
}

export function parseUpdateUsernameInstruction<
	TProgram extends string,
	TAccountMetas extends readonly AccountMeta[]
>(
	instruction: Instruction<TProgram> &
		InstructionWithAccounts<TAccountMetas> &
		InstructionWithData<ReadonlyUint8Array>
): ParsedUpdateUsernameInstruction<TProgram, TAccountMetas> {
	if (instruction.accounts.length < 2) {
		throw new SolanaError(SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS, {
			actualAccountMetas: instruction.accounts.length,
			expectedAccountMetas: 2
		})
	}
	let accountIndex = 0
	const getNextAccount = () => {
		const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!
		accountIndex += 1
		return accountMeta
	}
	return {
		programAddress: instruction.programAddress,
		accounts: { authority: getNextAccount(), profile: getNextAccount() },
		data: getUpdateUsernameInstructionDataDecoder().decode(instruction.data)
	}
}
