/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type Address,
	assertIsInstructionWithAccounts,
	type ClientWithPayer,
	type ClientWithTransactionPlanning,
	type ClientWithTransactionSending,
	containsBytes,
	getU8Encoder,
	type Instruction,
	type InstructionWithData,
	type ReadonlyUint8Array,
	SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_INSTRUCTION,
	SOLANA_ERROR__PROGRAM_CLIENTS__UNRECOGNIZED_INSTRUCTION_TYPE,
	SolanaError
} from "@solana/kit"
import {
	addSelfPlanAndSendFunctions,
	type SelfPlanAndSendFunctions
} from "@solana/program-client-core"
import {
	type CreateMintInput,
	getCreateMintInstruction,
	getTransferMintInstruction,
	type ParsedCreateMintInstruction,
	type ParsedTransferMintInstruction,
	parseCreateMintInstruction,
	parseTransferMintInstruction,
	type TransferMintInput
} from "../instructions"

export const BASIC_MINT_PROGRAM_ADDRESS =
	"8F1XtWR4wTs37nnutBvd2MWpCTfb7XAciFYkw5XHaENj" as Address<"8F1XtWR4wTs37nnutBvd2MWpCTfb7XAciFYkw5XHaENj">

export enum BasicMintInstruction {
	CreateMint,
	TransferMint
}

export function identifyBasicMintInstruction(
	instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): BasicMintInstruction {
	const data = "data" in instruction ? instruction.data : instruction
	if (containsBytes(data, getU8Encoder().encode(0), 0)) {
		return BasicMintInstruction.CreateMint
	}
	if (containsBytes(data, getU8Encoder().encode(1), 0)) {
		return BasicMintInstruction.TransferMint
	}
	throw new SolanaError(SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_INSTRUCTION, {
		instructionData: data,
		programName: "basicMint"
	})
}

export type ParsedBasicMintInstruction<
	TProgram extends string = "8F1XtWR4wTs37nnutBvd2MWpCTfb7XAciFYkw5XHaENj"
> =
	| ({
			instructionType: BasicMintInstruction.CreateMint
	  } & ParsedCreateMintInstruction<TProgram>)
	| ({
			instructionType: BasicMintInstruction.TransferMint
	  } & ParsedTransferMintInstruction<TProgram>)

export function parseBasicMintInstruction<TProgram extends string>(
	instruction: Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array>
): ParsedBasicMintInstruction<TProgram> {
	const instructionType = identifyBasicMintInstruction(instruction)
	switch (instructionType) {
		case BasicMintInstruction.CreateMint: {
			assertIsInstructionWithAccounts(instruction)
			return {
				instructionType: BasicMintInstruction.CreateMint,
				...parseCreateMintInstruction(instruction)
			}
		}
		case BasicMintInstruction.TransferMint: {
			assertIsInstructionWithAccounts(instruction)
			return {
				instructionType: BasicMintInstruction.TransferMint,
				...parseTransferMintInstruction(instruction)
			}
		}
		default:
			throw new SolanaError(SOLANA_ERROR__PROGRAM_CLIENTS__UNRECOGNIZED_INSTRUCTION_TYPE, {
				instructionType: instructionType as string,
				programName: "basicMint"
			})
	}
}

export type BasicMintPlugin = { instructions: BasicMintPluginInstructions }

export type BasicMintPluginInstructions = {
	createMint: (
		input: MakeOptional<CreateMintInput, "payer">
	) => ReturnType<typeof getCreateMintInstruction> & SelfPlanAndSendFunctions
	transferMint: (
		input: TransferMintInput
	) => ReturnType<typeof getTransferMintInstruction> & SelfPlanAndSendFunctions
}

export type BasicMintPluginRequirements = ClientWithPayer &
	ClientWithTransactionPlanning &
	ClientWithTransactionSending

export function basicMintProgram() {
	return <T extends BasicMintPluginRequirements>(client: T) => {
		return {
			...client,
			basicMint: <BasicMintPlugin>{
				instructions: {
					createMint: input =>
						addSelfPlanAndSendFunctions(
							client,
							getCreateMintInstruction({
								...input,
								payer: input.payer ?? client.payer
							})
						),
					transferMint: input =>
						addSelfPlanAndSendFunctions(client, getTransferMintInstruction(input))
				}
			}
		}
	}
}

type MakeOptional<T, K extends keyof T> = Omit<T, K> & Partial<Pick<T, K>>
